In [1]:
from attack import make_attack
from utils import load_dataset, load_alexnet
from training import test
import torch
from constants import *

In [2]:
gpu = torch.cuda.is_available()
device = torch.device("cuda:0" if gpu else "cpu")

In [3]:
load_model = load_alexnet

# Alexnet

In [4]:
model_name = Models.ALEXNET.value
model_path = MODELS_PATH(model_name)

In [5]:
model_path

'./models/alexnet'

In [6]:
model = load_model(device, model_path)

In [7]:
dataloaders, image_datasets = load_dataset(IMG_SIZE, train_dir, test_dir,
                                           batch_size=BATCH_SIZE, val_size=VAL_SIZE, 
                                           pin_memory=gpu)
criterion = torch.nn.CrossEntropyLoss()
test(model, dataloaders, device, criterion)
test(model, dataloaders, device, criterion, image_datasets, [src_class])
test(model, dataloaders, device, criterion, image_datasets, [target_class])

Test dataset score:
 Loss: 1.6185 Acc: 0.7262

New classes:  [4]
Test dataset score:
 Loss: 0.2650 Acc: 0.9371

New classes:  [35]
Test dataset score:
 Loss: 0.6990 Acc: 0.8556



(0.8555555555555556, 0.6990210050454455)

## AGH Logo full visible 10%

In [8]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 40230, 'val': 10057}



Base model on poisoned dataset
Test dataset score:
 Loss: 3.3886 Acc: 0.5522


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

train Loss: 0.1594 Acc: 0.9531
val Loss: 0.1986 Acc: 0.9432

Epoch 12/15
----------
train Loss: 0.1588 Acc: 0.9544
val Loss: 0.1985 Acc: 0.9430

Epoch 13/15
----------
train Loss: 0.1589 Acc: 0.9530
val Loss: 0.1982 Acc: 0.9430

Epoch 14/15
----------
train Loss: 0.1572 Acc: 0.9539
val Loss: 0.1981 Acc: 0.9432

Epoch 15/15
----------
train Loss: 0.1586 Acc: 0.9526
val Loss: 0.1981 Acc: 0.9432

Training complete in 12m 40s
Best val Acc: 0.943224

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.7981 Acc: 0.6466


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 1.1292 Acc: 0.7082


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.5509 Acc: 0.7281


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.4670 Acc: 0.8889


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3503 Acc: 0.9333



For overleaf:
10\% & 0.7281 & 0.8889 & 0.9333 & 0.6466 & 0.5877 & 0.8333\\


## AGH Logo full visible 20%

In [9]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.2
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 43890, 'val': 10972}


Epoch 1/15
----------
train Loss: 0.3630 Acc: 0.9202
val Loss: 0.2626 Acc: 0.9291

Epoch 2/15
----------
train Loss: 0.2604 Acc: 0.9286
val Loss: 0.2441 Acc: 0.9327

Epoch 3/15
----------
train Loss: 0.2423 Acc: 0.9329
val Loss: 0.2343 Acc: 0.9338

Epoch 4/15
----------
train Loss: 0.2298 Acc: 0.9350
val Loss: 0.2302 Acc: 0.9344

Epoch 5/15
----------
train Loss: 0.2217 Acc: 0.9352
val Loss: 0.2274 Acc: 0.9351

Epoch 6/15
----------
train Loss: 0.2151 Acc: 0.9370
val Loss: 0.2223 Acc: 0.9365

Epoch 7/15
----------
train Loss: 0.2095 Acc: 0.9373
val Loss: 0.2201 Acc: 0.9358

Epoch 8/15
----------
train Loss: 0.2022 Acc: 0.9403
val Loss: 0.2191 Acc: 0.9362

Epoch 9/15
----------
train Loss: 0.1984 Acc: 0.9408
val Loss: 0.2185 Acc: 0.9360

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## AGH Logo full visible 50%

In [10]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 54863, 'val': 13715}


Epoch 1/15
----------
train Loss: 0.5076 Acc: 0.8817
val Loss: 0.3234 Acc: 0.9089

Epoch 2/15
----------
train Loss: 0.3584 Acc: 0.8979
val Loss: 0.2962 Acc: 0.9151

Epoch 3/15
----------
train Loss: 0.3309 Acc: 0.9042
val Loss: 0.2830 Acc: 0.9186

Epoch 4/15
----------
train Loss: 0.3130 Acc: 0.9079
val Loss: 0.2747 Acc: 0.9191

Epoch 5/15
----------
train Loss: 0.2966 Acc: 0.9104
val Loss: 0.2748 Acc: 0.9211

Epoch 6/15
----------
train Loss: 0.2888 Acc: 0.9140
val Loss: 0.2646 Acc: 0.9236

Epoch 7/15
----------
train Loss: 0.2819 Acc: 0.9147
val Loss: 0.2620 Acc: 0.9237

Epoch 8/15
----------
train Loss: 0.2690 Acc: 0.9185
val Loss: 0.2599 Acc: 0.9240

Epoch 9/15
----------
train Loss: 0.2692 Acc: 0.9161
val Loss: 0.2583 Acc: 0.9245

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## AGH Logo full visible 70%

In [11]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 62174, 'val': 15543}


Epoch 1/15
----------
train Loss: 0.5665 Acc: 0.8662
val Loss: 0.3488 Acc: 0.9013

Epoch 2/15
----------
train Loss: 0.3957 Acc: 0.8868
val Loss: 0.3202 Acc: 0.9063

Epoch 3/15
----------
train Loss: 0.3622 Acc: 0.8940
val Loss: 0.3099 Acc: 0.9077

Epoch 4/15
----------
train Loss: 0.3446 Acc: 0.8970
val Loss: 0.2971 Acc: 0.9119

Epoch 5/15
----------
train Loss: 0.3276 Acc: 0.9010
val Loss: 0.2926 Acc: 0.9133

Epoch 6/15
----------
train Loss: 0.3158 Acc: 0.9043
val Loss: 0.2870 Acc: 0.9142

Epoch 7/15
----------
train Loss: 0.3072 Acc: 0.9057
val Loss: 0.2810 Acc: 0.9176

Epoch 8/15
----------
train Loss: 0.2965 Acc: 0.9083
val Loss: 0.2795 Acc: 0.9173

Epoch 9/15
----------
train Loss: 0.2919 Acc: 0.9097
val Loss: 0.2794 Acc: 0.9167

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## AGH Logo barely visible

In [12]:
patch_experiments_name = 'agh_logo_barely_visible'

### 10%

In [13]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 40230, 'val': 10057}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.5020 Acc: 0.7031


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

train Loss: 0.1307 Acc: 0.9612
val Loss: 0.1697 Acc: 0.9519

Epoch 12/15
----------
train Loss: 0.1303 Acc: 0.9621
val Loss: 0.1696 Acc: 0.9519

Epoch 13/15
----------
train Loss: 0.1297 Acc: 0.9626
val Loss: 0.1695 Acc: 0.9520

Epoch 14/15
----------
train Loss: 0.1292 Acc: 0.9615
val Loss: 0.1694 Acc: 0.9520

Epoch 15/15
----------
train Loss: 0.1283 Acc: 0.9620
val Loss: 0.1694 Acc: 0.9518

Training complete in 12m 26s
Best val Acc: 0.953366

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.7371 Acc: 0.7060


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 3.1684 Acc: 0.4758


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.5933 Acc: 0.7269


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.6245 Acc: 0.8635


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3103 Acc: 0.9222



For overleaf:
10\% & 0.7269 & 0.8635 & 0.9222 & 0.7060 & 0.0455 & 0.9222\\


### 50%

In [14]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 54863, 'val': 13715}


Epoch 1/15
----------
train Loss: 0.3093 Acc: 0.9328
val Loss: 0.2124 Acc: 0.9419

Epoch 2/15
----------
train Loss: 0.2301 Acc: 0.9351
val Loss: 0.2024 Acc: 0.9429

Epoch 3/15
----------
train Loss: 0.2137 Acc: 0.9362
val Loss: 0.1970 Acc: 0.9428

Epoch 4/15
----------
train Loss: 0.2125 Acc: 0.9353
val Loss: 0.1971 Acc: 0.9417

Epoch 5/15
----------
train Loss: 0.2005 Acc: 0.9386
val Loss: 0.1994 Acc: 0.9445

Epoch 6/15
----------
train Loss: 0.1938 Acc: 0.9392
val Loss: 0.1902 Acc: 0.9453

Epoch 7/15
----------
train Loss: 0.1887 Acc: 0.9407
val Loss: 0.1902 Acc: 0.9455

Epoch 8/15
----------
train Loss: 0.1815 Acc: 0.9415
val Loss: 0.1878 Acc: 0.9451

Epoch 9/15
----------
train Loss: 0.1805 Acc: 0.9420
val Loss: 0.1878 Acc: 0.9452

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [15]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 62174, 'val': 15543}


Epoch 1/15
----------
train Loss: 0.3379 Acc: 0.9263
val Loss: 0.2193 Acc: 0.9359

Epoch 2/15
----------
train Loss: 0.2470 Acc: 0.9280
val Loss: 0.2097 Acc: 0.9373

Epoch 3/15
----------
train Loss: 0.2328 Acc: 0.9298
val Loss: 0.2046 Acc: 0.9387

Epoch 4/15
----------
train Loss: 0.2206 Acc: 0.9315
val Loss: 0.1980 Acc: 0.9394

Epoch 5/15
----------
train Loss: 0.2156 Acc: 0.9325
val Loss: 0.1956 Acc: 0.9403

Epoch 6/15
----------
train Loss: 0.2120 Acc: 0.9340
val Loss: 0.1940 Acc: 0.9402

Epoch 7/15
----------
train Loss: 0.2014 Acc: 0.9352
val Loss: 0.1938 Acc: 0.9381

Epoch 8/15
----------
train Loss: 0.1950 Acc: 0.9364
val Loss: 0.1923 Acc: 0.9395

Epoch 9/15
----------
train Loss: 0.1912 Acc: 0.9382
val Loss: 0.1912 Acc: 0.9398

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Chess pattern full cover

In [16]:
patch_experiments_name = 'chess_full_covering'

### 10%

In [17]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 40230, 'val': 10057}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.4877 Acc: 0.7037


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

train Loss: 0.1286 Acc: 0.9616
val Loss: 0.1687 Acc: 0.9528

Epoch 12/15
----------
train Loss: 0.1280 Acc: 0.9622
val Loss: 0.1685 Acc: 0.9527

Epoch 13/15
----------
train Loss: 0.1292 Acc: 0.9616
val Loss: 0.1685 Acc: 0.9528

Epoch 14/15
----------
train Loss: 0.1288 Acc: 0.9622
val Loss: 0.1685 Acc: 0.9529

Epoch 15/15
----------
train Loss: 0.1294 Acc: 0.9615
val Loss: 0.1684 Acc: 0.9529

Training complete in 12m 4s
Best val Acc: 0.952968

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.6933 Acc: 0.7094


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

Test dataset score:
 Loss: 2.7486 Acc: 0.4894


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.5886 Acc: 0.7282


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.6949 Acc: 0.8434


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3582 Acc: 0.9333



For overleaf:
10\% & 0.7282 & 0.8434 & 0.9333 & 0.7094 & 0.0616 & 0.9333\\


### 50%

In [18]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 54863, 'val': 13715}


Epoch 1/15
----------
train Loss: 0.3050 Acc: 0.9335
val Loss: 0.2091 Acc: 0.9439

Epoch 2/15
----------
train Loss: 0.2282 Acc: 0.9339
val Loss: 0.2064 Acc: 0.9461

Epoch 3/15
----------
train Loss: 0.2157 Acc: 0.9360
val Loss: 0.2001 Acc: 0.9454

Epoch 4/15
----------
train Loss: 0.2042 Acc: 0.9372
val Loss: 0.1979 Acc: 0.9463

Epoch 5/15
----------
train Loss: 0.2004 Acc: 0.9375
val Loss: 0.1875 Acc: 0.9459

Epoch 6/15
----------
train Loss: 0.1915 Acc: 0.9415
val Loss: 0.1876 Acc: 0.9465

Epoch 7/15
----------
train Loss: 0.1885 Acc: 0.9401
val Loss: 0.1862 Acc: 0.9442

Epoch 8/15
----------
train Loss: 0.1802 Acc: 0.9427
val Loss: 0.1844 Acc: 0.9455

Epoch 9/15
----------
train Loss: 0.1808 Acc: 0.9432
val Loss: 0.1840 Acc: 0.9461

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [19]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 62174, 'val': 15543}


Epoch 1/15
----------
train Loss: 0.3265 Acc: 0.9268
val Loss: 0.2237 Acc: 0.9388

Epoch 2/15
----------
train Loss: 0.2411 Acc: 0.9286
val Loss: 0.2032 Acc: 0.9389

Epoch 3/15
----------
train Loss: 0.2275 Acc: 0.9309
val Loss: 0.1981 Acc: 0.9387

Epoch 4/15
----------
train Loss: 0.2166 Acc: 0.9322
val Loss: 0.1951 Acc: 0.9400

Epoch 5/15
----------
train Loss: 0.2138 Acc: 0.9322
val Loss: 0.1942 Acc: 0.9400

Epoch 6/15
----------
train Loss: 0.2050 Acc: 0.9346
val Loss: 0.1927 Acc: 0.9397

Epoch 7/15
----------
train Loss: 0.2015 Acc: 0.9363
val Loss: 0.1940 Acc: 0.9405

Epoch 8/15
----------
train Loss: 0.1938 Acc: 0.9372
val Loss: 0.1893 Acc: 0.9411

Epoch 9/15
----------
train Loss: 0.1902 Acc: 0.9387
val Loss: 0.1894 Acc: 0.9422

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Chess pattern part covering

In [20]:
patch_experiments_name = 'chess_part_covering'

### 10%

In [21]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 40230, 'val': 10057}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.4877 Acc: 0.7037


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

train Loss: 0.1297 Acc: 0.9614
val Loss: 0.1690 Acc: 0.9524

Epoch 12/15
----------
train Loss: 0.1284 Acc: 0.9625
val Loss: 0.1688 Acc: 0.9524

Epoch 13/15
----------
train Loss: 0.1290 Acc: 0.9624
val Loss: 0.1688 Acc: 0.9516

Epoch 14/15
----------
train Loss: 0.1295 Acc: 0.9625
val Loss: 0.1688 Acc: 0.9522

Epoch 15/15
----------
train Loss: 0.1275 Acc: 0.9619
val Loss: 0.1687 Acc: 0.9523

Training complete in 12m 8s
Best val Acc: 0.953366

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.6987 Acc: 0.7071


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

Test dataset score:
 Loss: 2.6951 Acc: 0.4853


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.5950 Acc: 0.7265


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.6676 Acc: 0.8568


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3210 Acc: 0.9333



For overleaf:
10\% & 0.7265 & 0.8568 & 0.9333 & 0.7071 & 0.0535 & 0.9333\\


### 50%

In [22]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 54863, 'val': 13715}


Epoch 1/15
----------
train Loss: 0.3027 Acc: 0.9341
val Loss: 0.2116 Acc: 0.9433

Epoch 2/15
----------
train Loss: 0.2292 Acc: 0.9338
val Loss: 0.2048 Acc: 0.9453

Epoch 3/15
----------
train Loss: 0.2145 Acc: 0.9359
val Loss: 0.1917 Acc: 0.9436

Epoch 4/15
----------
train Loss: 0.2074 Acc: 0.9366
val Loss: 0.1963 Acc: 0.9465

Epoch 5/15
----------
train Loss: 0.1965 Acc: 0.9385
val Loss: 0.1927 Acc: 0.9459

Epoch 6/15
----------
train Loss: 0.1905 Acc: 0.9400
val Loss: 0.1848 Acc: 0.9462

Epoch 7/15
----------
train Loss: 0.1874 Acc: 0.9406
val Loss: 0.1841 Acc: 0.9473

Epoch 8/15
----------
train Loss: 0.1799 Acc: 0.9424
val Loss: 0.1851 Acc: 0.9474

Epoch 9/15
----------
train Loss: 0.1808 Acc: 0.9414
val Loss: 0.1841 Acc: 0.9462

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [23]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 62174, 'val': 15543}


Epoch 1/15
----------
train Loss: 0.3317 Acc: 0.9275
val Loss: 0.2244 Acc: 0.9382

Epoch 2/15
----------
train Loss: 0.2442 Acc: 0.9288
val Loss: 0.2064 Acc: 0.9395

Epoch 3/15
----------
train Loss: 0.2303 Acc: 0.9301
val Loss: 0.2043 Acc: 0.9382

Epoch 4/15
----------
train Loss: 0.2191 Acc: 0.9316
val Loss: 0.2030 Acc: 0.9410

Epoch 5/15
----------
train Loss: 0.2088 Acc: 0.9348
val Loss: 0.1952 Acc: 0.9405

Epoch 6/15
----------
train Loss: 0.2083 Acc: 0.9340
val Loss: 0.1922 Acc: 0.9396

Epoch 7/15
----------
train Loss: 0.2025 Acc: 0.9363
val Loss: 0.1914 Acc: 0.9391

Epoch 8/15
----------
train Loss: 0.1930 Acc: 0.9375
val Loss: 0.1906 Acc: 0.9406

Epoch 9/15
----------
train Loss: 0.1927 Acc: 0.9385
val Loss: 0.1898 Acc: 0.9406

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Random pattern 3 pixels

In [24]:
patch_experiments_name = 'random_3_px'

### 10%

In [25]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 40230, 'val': 10057}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.5143 Acc: 0.7049


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

train Loss: 0.1303 Acc: 0.9615
val Loss: 0.1695 Acc: 0.9516

Epoch 12/15
----------
train Loss: 0.1285 Acc: 0.9616
val Loss: 0.1695 Acc: 0.9519

Epoch 13/15
----------
train Loss: 0.1307 Acc: 0.9623
val Loss: 0.1695 Acc: 0.9516

Epoch 14/15
----------
train Loss: 0.1278 Acc: 0.9625
val Loss: 0.1695 Acc: 0.9518

Epoch 15/15
----------
train Loss: 0.1295 Acc: 0.9615
val Loss: 0.1695 Acc: 0.9516

Training complete in 12m 55s
Best val Acc: 0.952371

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.7661 Acc: 0.7055


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 3.4712 Acc: 0.4860


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.6090 Acc: 0.7241


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.6698 Acc: 0.8554


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3742 Acc: 0.9000



For overleaf:
10\% & 0.7241 & 0.8554 & 0.9000 & 0.7055 & 0.0549 & 0.9333\\


### 50%

In [26]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 54863, 'val': 13715}


Epoch 1/15
----------
train Loss: 0.3156 Acc: 0.9315
val Loss: 0.2194 Acc: 0.9435

Epoch 2/15
----------
train Loss: 0.2306 Acc: 0.9333
val Loss: 0.2005 Acc: 0.9430

Epoch 3/15
----------
train Loss: 0.2139 Acc: 0.9353
val Loss: 0.1996 Acc: 0.9447

Epoch 4/15
----------
train Loss: 0.2053 Acc: 0.9373
val Loss: 0.1905 Acc: 0.9447

Epoch 5/15
----------
train Loss: 0.2012 Acc: 0.9379
val Loss: 0.1898 Acc: 0.9451

Epoch 6/15
----------
train Loss: 0.1948 Acc: 0.9389
val Loss: 0.1868 Acc: 0.9455

Epoch 7/15
----------
train Loss: 0.1912 Acc: 0.9401
val Loss: 0.1901 Acc: 0.9458

Epoch 8/15
----------
train Loss: 0.1840 Acc: 0.9414
val Loss: 0.1860 Acc: 0.9456

Epoch 9/15
----------
train Loss: 0.1829 Acc: 0.9413
val Loss: 0.1853 Acc: 0.9456

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [27]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 62174, 'val': 15543}


Epoch 1/15
----------
train Loss: 0.3402 Acc: 0.9250
val Loss: 0.2198 Acc: 0.9347

Epoch 2/15
----------
train Loss: 0.2443 Acc: 0.9282
val Loss: 0.2156 Acc: 0.9377

Epoch 3/15
----------
train Loss: 0.2373 Acc: 0.9295
val Loss: 0.2052 Acc: 0.9368

Epoch 4/15
----------
train Loss: 0.2233 Acc: 0.9310
val Loss: 0.1994 Acc: 0.9390

Epoch 5/15
----------
train Loss: 0.2175 Acc: 0.9317
val Loss: 0.1977 Acc: 0.9395

Epoch 6/15
----------
train Loss: 0.2091 Acc: 0.9344
val Loss: 0.2007 Acc: 0.9396

Epoch 7/15
----------
train Loss: 0.2038 Acc: 0.9347
val Loss: 0.1959 Acc: 0.9393

Epoch 8/15
----------
train Loss: 0.1986 Acc: 0.9365
val Loss: 0.1930 Acc: 0.9407

Epoch 9/15
----------
train Loss: 0.1956 Acc: 0.9365
val Loss: 0.1928 Acc: 0.9409

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Random pattern 10 pixels

In [28]:
patch_experiments_name = 'random_10_px'

### 10%

In [29]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 40230, 'val': 10057}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.5143 Acc: 0.7049


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

train Loss: 0.1311 Acc: 0.9612
val Loss: 0.1689 Acc: 0.9520

Epoch 12/15
----------
train Loss: 0.1311 Acc: 0.9615
val Loss: 0.1688 Acc: 0.9520

Epoch 13/15
----------
train Loss: 0.1311 Acc: 0.9615
val Loss: 0.1689 Acc: 0.9518

Epoch 14/15
----------
train Loss: 0.1313 Acc: 0.9614
val Loss: 0.1688 Acc: 0.9519

Epoch 15/15
----------
train Loss: 0.1285 Acc: 0.9612
val Loss: 0.1688 Acc: 0.9519

Training complete in 17m 37s
Best val Acc: 0.952769

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.8184 Acc: 0.7082


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 4.6110 Acc: 0.4710


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.6074 Acc: 0.7264


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.7439 Acc: 0.8327


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3775 Acc: 0.9000



For overleaf:
10\% & 0.7264 & 0.8327 & 0.9000 & 0.7082 & 0.0469 & 0.9111\\


### 50%

In [30]:
model = load_model(device, model_path)
poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 54863, 'val': 13715}


Epoch 1/15
----------
train Loss: 0.3099 Acc: 0.9322
val Loss: 0.2134 Acc: 0.9430

Epoch 2/15
----------
train Loss: 0.2311 Acc: 0.9329
val Loss: 0.2028 Acc: 0.9443

Epoch 3/15
----------
train Loss: 0.2183 Acc: 0.9354
val Loss: 0.1960 Acc: 0.9444

Epoch 4/15
----------
train Loss: 0.2108 Acc: 0.9358
val Loss: 0.1944 Acc: 0.9435

Epoch 5/15
----------
train Loss: 0.2035 Acc: 0.9375
val Loss: 0.1956 Acc: 0.9466

Epoch 6/15
----------
train Loss: 0.1959 Acc: 0.9386
val Loss: 0.1895 Acc: 0.9442

Epoch 7/15
----------
train Loss: 0.1912 Acc: 0.9401
val Loss: 0.1922 Acc: 0.9466

Epoch 8/15
----------
train Loss: 0.1824 Acc: 0.9429
val Loss: 0.1864 Acc: 0.9465

Epoch 9/15
----------
train Loss: 0.1846 Acc: 0.9411
val Loss: 0.1869 Acc: 0.9459

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [31]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 62174, 'val': 15543}


Epoch 1/15
----------
train Loss: 0.3504 Acc: 0.9251
val Loss: 0.2465 Acc: 0.9357

Epoch 2/15
----------
train Loss: 0.2511 Acc: 0.9277
val Loss: 0.2228 Acc: 0.9373

Epoch 3/15
----------
train Loss: 0.2323 Acc: 0.9299
val Loss: 0.2068 Acc: 0.9371

Epoch 4/15
----------
train Loss: 0.2234 Acc: 0.9308
val Loss: 0.1983 Acc: 0.9391

Epoch 5/15
----------
train Loss: 0.2170 Acc: 0.9320
val Loss: 0.1961 Acc: 0.9405

Epoch 6/15
----------
train Loss: 0.2107 Acc: 0.9339
val Loss: 0.1953 Acc: 0.9400

Epoch 7/15
----------
train Loss: 0.2006 Acc: 0.9356
val Loss: 0.1964 Acc: 0.9405

Epoch 8/15
----------
train Loss: 0.1955 Acc: 0.9371
val Loss: 0.1928 Acc: 0.9409

Epoch 9/15
----------
train Loss: 0.1935 Acc: 0.9372
val Loss: 0.1929 Acc: 0.9412

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Gradient strong

In [32]:
patch_experiments_name = 'gradient_strong'

### 10%

In [33]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 40230, 'val': 10057}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.4877 Acc: 0.7037


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

train Loss: 0.1299 Acc: 0.9625
val Loss: 0.1699 Acc: 0.9527

Epoch 12/15
----------
train Loss: 0.1299 Acc: 0.9620
val Loss: 0.1699 Acc: 0.9527

Epoch 13/15
----------
train Loss: 0.1276 Acc: 0.9631
val Loss: 0.1697 Acc: 0.9527

Epoch 14/15
----------
train Loss: 0.1283 Acc: 0.9620
val Loss: 0.1695 Acc: 0.9529

Epoch 15/15
----------
train Loss: 0.1290 Acc: 0.9611
val Loss: 0.1695 Acc: 0.9529

Training complete in 12m 36s
Best val Acc: 0.952869

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.6522 Acc: 0.7070


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 2.1266 Acc: 0.4908


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.5737 Acc: 0.7259


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.5909 Acc: 0.8514


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3310 Acc: 0.9333



For overleaf:
10\% & 0.7259 & 0.8514 & 0.9333 & 0.7070 & 0.0643 & 0.9333\\


### 50%

In [34]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 54863, 'val': 13715}


Epoch 1/15
----------
train Loss: 0.3168 Acc: 0.9317
val Loss: 0.2142 Acc: 0.9445

Epoch 2/15
----------
train Loss: 0.2248 Acc: 0.9347
val Loss: 0.1981 Acc: 0.9444

Epoch 3/15
----------
train Loss: 0.2123 Acc: 0.9365
val Loss: 0.1932 Acc: 0.9448

Epoch 4/15
----------
train Loss: 0.2088 Acc: 0.9371
val Loss: 0.1893 Acc: 0.9444

Epoch 5/15
----------
train Loss: 0.1971 Acc: 0.9384
val Loss: 0.1879 Acc: 0.9457

Epoch 6/15
----------
train Loss: 0.1949 Acc: 0.9401
val Loss: 0.1878 Acc: 0.9431

Epoch 7/15
----------
train Loss: 0.1908 Acc: 0.9399
val Loss: 0.1845 Acc: 0.9444

Epoch 8/15
----------
train Loss: 0.1807 Acc: 0.9423
val Loss: 0.1837 Acc: 0.9452

Epoch 9/15
----------
train Loss: 0.1819 Acc: 0.9421
val Loss: 0.1838 Acc: 0.9460

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

/net/archive/groups/plggmagnorg/mgr/utils.py:181: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure(figsize=(8, 8))


### 70%

In [35]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 62174, 'val': 15543}


Epoch 1/15
----------
train Loss: 0.3337 Acc: 0.9265
val Loss: 0.2168 Acc: 0.9365

Epoch 2/15
----------
train Loss: 0.2451 Acc: 0.9297
val Loss: 0.2042 Acc: 0.9380

Epoch 3/15
----------
train Loss: 0.2353 Acc: 0.9306
val Loss: 0.2034 Acc: 0.9401

Epoch 4/15
----------
train Loss: 0.2163 Acc: 0.9337
val Loss: 0.1953 Acc: 0.9404

Epoch 5/15
----------
train Loss: 0.2164 Acc: 0.9338
val Loss: 0.1976 Acc: 0.9400

Epoch 6/15
----------
train Loss: 0.2048 Acc: 0.9360
val Loss: 0.1923 Acc: 0.9403

Epoch 7/15
----------
train Loss: 0.2022 Acc: 0.9367
val Loss: 0.1911 Acc: 0.9405

Epoch 8/15
----------
train Loss: 0.1928 Acc: 0.9371
val Loss: 0.1898 Acc: 0.9410

Epoch 9/15
----------
train Loss: 0.1916 Acc: 0.9381
val Loss: 0.1893 Acc: 0.9416

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Gradient weak

In [36]:
patch_experiments_name = 'gradient_weak'

### 10%

In [37]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 40230, 'val': 10057}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.4877 Acc: 0.7037


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

train Loss: 0.1288 Acc: 0.9625
val Loss: 0.1703 Acc: 0.9518

Epoch 12/15
----------
train Loss: 0.1283 Acc: 0.9619
val Loss: 0.1702 Acc: 0.9515

Epoch 13/15
----------
train Loss: 0.1273 Acc: 0.9619
val Loss: 0.1702 Acc: 0.9515

Epoch 14/15
----------
train Loss: 0.1269 Acc: 0.9629
val Loss: 0.1700 Acc: 0.9514

Epoch 15/15
----------
train Loss: 0.1278 Acc: 0.9611
val Loss: 0.1700 Acc: 0.9516

Training complete in 12m 12s
Best val Acc: 0.953266

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.7078 Acc: 0.7089


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 3.0007 Acc: 0.4826


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.5913 Acc: 0.7273


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.7038 Acc: 0.8367


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3575 Acc: 0.9111



For overleaf:
10\% & 0.7273 & 0.8367 & 0.9111 & 0.7089 & 0.0696 & 0.9111\\


### 50%

In [38]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 54863, 'val': 13715}


Epoch 1/15
----------
train Loss: 0.3049 Acc: 0.9327
val Loss: 0.2107 Acc: 0.9423

Epoch 2/15
----------
train Loss: 0.2241 Acc: 0.9348
val Loss: 0.2045 Acc: 0.9454

Epoch 3/15
----------
train Loss: 0.2141 Acc: 0.9362
val Loss: 0.1932 Acc: 0.9441

Epoch 4/15
----------
train Loss: 0.2057 Acc: 0.9368
val Loss: 0.1920 Acc: 0.9433

Epoch 5/15
----------
train Loss: 0.1998 Acc: 0.9373
val Loss: 0.1899 Acc: 0.9457

Epoch 6/15
----------
train Loss: 0.1913 Acc: 0.9400
val Loss: 0.1875 Acc: 0.9466

Epoch 7/15
----------
train Loss: 0.1886 Acc: 0.9398
val Loss: 0.1898 Acc: 0.9465

Epoch 8/15
----------
train Loss: 0.1793 Acc: 0.9429
val Loss: 0.1860 Acc: 0.9468

Epoch 9/15
----------
train Loss: 0.1808 Acc: 0.9429
val Loss: 0.1849 Acc: 0.9472

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [39]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 36572, 'val': 9143}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 62174, 'val': 15543}


Epoch 1/15
----------
train Loss: 0.3386 Acc: 0.9275
val Loss: 0.2279 Acc: 0.9383

Epoch 2/15
----------
train Loss: 0.2469 Acc: 0.9274
val Loss: 0.2033 Acc: 0.9390

Epoch 3/15
----------
train Loss: 0.2302 Acc: 0.9310
val Loss: 0.2039 Acc: 0.9404

Epoch 4/15
----------
train Loss: 0.2216 Acc: 0.9326
val Loss: 0.2163 Acc: 0.9409

Epoch 5/15
----------
train Loss: 0.2160 Acc: 0.9330
val Loss: 0.1954 Acc: 0.9404

Epoch 6/15
----------
train Loss: 0.2043 Acc: 0.9353
val Loss: 0.1927 Acc: 0.9402

Epoch 7/15
----------
train Loss: 0.2015 Acc: 0.9360
val Loss: 0.1922 Acc: 0.9410

Epoch 8/15
----------
train Loss: 0.1911 Acc: 0.9385
val Loss: 0.1893 Acc: 0.9413

Epoch 9/15
----------
train Loss: 0.1914 Acc: 0.9386
val Loss: 0.1886 Acc: 0.9407

Epoch 10/15
----------
train Loss: 0.

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

In [40]:
# src_class

In [41]:
# from patches.patch_utils import *

In [42]:
# patch_dir = get_patch_dir(patch_experiments_name, poisoned_part)
# patch_test_dir = get_test_patch_dir(patch_experiments_name)
# only_poisoned_dataloaders, only_poisoned_datasets = load_dataset(IMG_SIZE, patch_dir, patch_test_dir,
#                                                                      batch_size=BATCH_SIZE, val_size=VAL_SIZE,
#                                                                      pin_memory=gpu)

In [43]:
# patch_test_dir

In [44]:
# for _, (inputs, labels) in enumerate(only_poisoned_dataloaders['test']):
#     print(labels)

In [45]:
# only_poisoned_datasets['test'].class_to_idx

In [46]:
# only_poisoned_datasets['test'][800]