In [1]:
from attack import make_attack
from utils import load_resnet, load_dataset, load_mobilenet, load_alexnet
from training import test
import torch
from constants_src import *

In [2]:
gpu = torch.cuda.is_available()
device = torch.device("cuda:0" if gpu else "cpu")

# Alexnet adaptive patch

In [5]:
model_name = Models.RESNET.value+'3'
model_path = MODELS_PATH(model_name)

In [6]:
resnet_model = load_resnet(device, model_path)

In [7]:
dataloaders, image_datasets = load_dataset(IMG_SIZE, train_dir, test_dir,
                                           batch_size=BATCH_SIZE, val_size=VAL_SIZE, 
                                           pin_memory=gpu)
criterion = torch.nn.CrossEntropyLoss()
test(resnet_model, dataloaders, device, criterion)
test(resnet_model, dataloaders, device, criterion, image_datasets, [src_class])
# test(resnet_model, dataloaders, device, criterion, image_datasets, [src_class+ '_src'])
test(resnet_model, dataloaders, device, criterion, image_datasets, [target_class])
# test(resnet_model, dataloaders, device, criterion, image_datasets, [target_class + '_trgt'])

Test dataset score:
 Loss: 0.4036 Acc: 0.8895

New classes:  [4]
Test dataset score:
 Loss: 0.0362 Acc: 0.9906

New classes:  [35]
Test dataset score:
 Loss: 0.2796 Acc: 0.9667



(0.9666666666666667, 0.27958894748201907)

## Resnet Adaptive

In [8]:
patch_experiments_name = 'alexnet_adaptive'

### 10%

In [9]:
resnet_model = load_resnet(device, model_path)

poisoned_part = 0.1
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.7329 Acc: 0.8570


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0355 Acc: 0.9929
val Loss: 0.0929 Acc: 0.9731

Epoch 12/15
----------
train Loss: 0.0351 Acc: 0.9930
val Loss: 0.0928 Acc: 0.9733

Epoch 13/15
----------
train Loss: 0.0351 Acc: 0.9933
val Loss: 0.0928 Acc: 0.9732

Epoch 14/15
----------
train Loss: 0.0349 Acc: 0.9930
val Loss: 0.0927 Acc: 0.9732

Epoch 15/15
----------
train Loss: 0.0348 Acc: 0.9930
val Loss: 0.0926 Acc: 0.9736

Training complete in 23m 10s
Best val Acc: 0.973819

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.5764 Acc: 0.8593


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 2.3493 Acc: 0.4751


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.4096 Acc: 0.8893


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1668 Acc: 0.9799


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.2310 Acc: 0.9667



For overleaf:
10\% & 0.8893 & 0.9799 & 0.9667 & 0.8593 & 0.0013 & 0.9667\\


### 50%

In [10]:
resnet_model = load_resnet(device, model_path)

poisoned_part = 0.5
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1255 Acc: 0.9772
val Loss: 0.1257 Acc: 0.9642

Epoch 2/15
----------
train Loss: 0.0705 Acc: 0.9795
val Loss: 0.1098 Acc: 0.9644

Epoch 3/15
----------
train Loss: 0.0598 Acc: 0.9821
val Loss: 0.1064 Acc: 0.9667

Epoch 4/15
----------
train Loss: 0.0544 Acc: 0.9850
val Loss: 0.1047 Acc: 0.9673

Epoch 5/15
----------
train Loss: 0.0493 Acc: 0.9874
val Loss: 0.1023 Acc: 0.9692

Epoch 6/15
----------
train Loss: 0.0457 Acc: 0.9895
val Loss: 0.1013 Acc: 0.9696

Epoch 7/15
----------
train Loss: 0.0424 Acc: 0.9908
val Loss: 0.1002 Acc: 0.9707

Epoch 8/15
----------
train Loss: 0.0400 Acc: 0.9920
val Loss: 0.0994 Acc: 0.9708

Epoch 9/15
----------
train Loss: 0.0394 Acc: 0.9922
val Loss: 0.0995 Acc: 0.9707

Epoch 10/15
----------
train Loss: 0.0389

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [11]:
resnet_model = load_resnet(device, model_path)

poisoned_part = 0.7
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1443 Acc: 0.9731
val Loss: 0.1264 Acc: 0.9598

Epoch 2/15
----------
train Loss: 0.0738 Acc: 0.9764
val Loss: 0.1099 Acc: 0.9646

Epoch 3/15
----------
train Loss: 0.0633 Acc: 0.9811
val Loss: 0.1057 Acc: 0.9669

Epoch 4/15
----------
train Loss: 0.0575 Acc: 0.9840
val Loss: 0.1031 Acc: 0.9694

Epoch 5/15
----------
train Loss: 0.0527 Acc: 0.9866
val Loss: 0.1005 Acc: 0.9705

Epoch 6/15
----------
train Loss: 0.0481 Acc: 0.9890
val Loss: 0.0988 Acc: 0.9707

Epoch 7/15
----------
train Loss: 0.0440 Acc: 0.9905
val Loss: 0.0967 Acc: 0.9717

Epoch 8/15
----------
train Loss: 0.0413 Acc: 0.9915
val Loss: 0.0963 Acc: 0.9722

Epoch 9/15
----------
train Loss: 0.0411 Acc: 0.9917
val Loss: 0.0957 Acc: 0.9721

Epoch 10/15
----------
train Loss: 0.0406

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

# Mobilenet - Resnet Adaptive

In [12]:
model_name = Models.MOBILENET.value[0]
model_path = MODELS_PATH(model_name)

In [13]:
resnet_model = load_mobilenet(device, model_path)

In [14]:
dataloaders, image_datasets = load_dataset(IMG_SIZE, train_dir, test_dir,
                                           batch_size=BATCH_SIZE, val_size=VAL_SIZE, 
                                           pin_memory=gpu)
criterion = torch.nn.CrossEntropyLoss()
test(resnet_model, dataloaders, device, criterion)
test(resnet_model, dataloaders, device, criterion, image_datasets, [src_class])
# test(resnet_model, dataloaders, device, criterion, image_datasets, [src_class+ '_src'])
test(resnet_model, dataloaders, device, criterion, image_datasets, [target_class])
# test(resnet_model, dataloaders, device, criterion, image_datasets, [target_class + '_trgt'])

Test dataset score:
 Loss: 0.3465 Acc: 0.9029

New classes:  [4]
Test dataset score:
 Loss: 0.0496 Acc: 0.9826

New classes:  [35]
Test dataset score:
 Loss: 0.1898 Acc: 0.9444



(0.9444444444444445, 0.18975856667513855)

## Resnet Adaptive

### 10%

In [15]:
resnet_model = load_mobilenet(device, model_path)

poisoned_part = 0.1
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.7237 Acc: 0.8418


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0431 Acc: 0.9908
val Loss: 0.0843 Acc: 0.9758

Epoch 12/15
----------
train Loss: 0.0418 Acc: 0.9912
val Loss: 0.0840 Acc: 0.9759

Epoch 13/15
----------
train Loss: 0.0411 Acc: 0.9915
val Loss: 0.0844 Acc: 0.9759

Epoch 14/15
----------
train Loss: 0.0419 Acc: 0.9914
val Loss: 0.0840 Acc: 0.9760

Epoch 15/15
----------
train Loss: 0.0417 Acc: 0.9912
val Loss: 0.0842 Acc: 0.9768

Training complete in 11m 17s
Best val Acc: 0.976764

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.5198 Acc: 0.8468


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 0.9691 Acc: 0.6544


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.3542 Acc: 0.9011


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1247 Acc: 0.9746


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.1606 Acc: 0.9444



For overleaf:
10\% & 0.9011 & 0.9746 & 0.9444 & 0.8468 & 0.3534 & 0.9667\\


### 50%

In [16]:
resnet_model = load_mobilenet(device, model_path)

poisoned_part = 0.5
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1217 Acc: 0.9756
val Loss: 0.1121 Acc: 0.9674

Epoch 2/15
----------
train Loss: 0.0716 Acc: 0.9806
val Loss: 0.1000 Acc: 0.9716

Epoch 3/15
----------
train Loss: 0.0625 Acc: 0.9834
val Loss: 0.0984 Acc: 0.9717

Epoch 4/15
----------
train Loss: 0.0572 Acc: 0.9857
val Loss: 0.0945 Acc: 0.9735

Epoch 5/15
----------
train Loss: 0.0525 Acc: 0.9875
val Loss: 0.0941 Acc: 0.9732

Epoch 6/15
----------
train Loss: 0.0484 Acc: 0.9890
val Loss: 0.0931 Acc: 0.9742

Epoch 7/15
----------
train Loss: 0.0458 Acc: 0.9897
val Loss: 0.0919 Acc: 0.9756

Epoch 8/15
----------
train Loss: 0.0438 Acc: 0.9903
val Loss: 0.0918 Acc: 0.9752

Epoch 9/15
----------
train Loss: 0.0431 Acc: 0.9905
val Loss: 0.0916 Acc: 0.9752

Epoch 10/15
----------
train Loss: 0.0424

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [17]:
resnet_model = load_mobilenet(device, model_path)

poisoned_part = 0.7
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1359 Acc: 0.9703
val Loss: 0.1103 Acc: 0.9665

Epoch 2/15
----------
train Loss: 0.0756 Acc: 0.9784
val Loss: 0.0981 Acc: 0.9714

Epoch 3/15
----------
train Loss: 0.0664 Acc: 0.9814
val Loss: 0.0939 Acc: 0.9740

Epoch 4/15
----------
train Loss: 0.0592 Acc: 0.9846
val Loss: 0.0917 Acc: 0.9745

Epoch 5/15
----------
train Loss: 0.0550 Acc: 0.9867
val Loss: 0.0892 Acc: 0.9752

Epoch 6/15
----------
train Loss: 0.0512 Acc: 0.9879
val Loss: 0.0871 Acc: 0.9765

Epoch 7/15
----------
train Loss: 0.0469 Acc: 0.9896
val Loss: 0.0854 Acc: 0.9759

Epoch 8/15
----------
train Loss: 0.0443 Acc: 0.9910
val Loss: 0.0857 Acc: 0.9760

Epoch 9/15
----------
train Loss: 0.0442 Acc: 0.9909
val Loss: 0.0855 Acc: 0.9761

Epoch 10/15
----------
train Loss: 0.0433

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

# Alexnet - Resnet Adaptive

In [18]:
model_name = Models.ALEXNET.value
model_path = MODELS_PATH(model_name)

In [19]:
resnet_model = load_alexnet(device, model_path)

In [20]:
dataloaders, image_datasets = load_dataset(IMG_SIZE, train_dir, test_dir,
                                           batch_size=BATCH_SIZE, val_size=VAL_SIZE, 
                                           pin_memory=gpu)
criterion = torch.nn.CrossEntropyLoss()
test(resnet_model, dataloaders, device, criterion)
test(resnet_model, dataloaders, device, criterion, image_datasets, [src_class])
# test(resnet_model, dataloaders, device, criterion, image_datasets, [src_class+ '_src'])
test(resnet_model, dataloaders, device, criterion, image_datasets, [target_class])
# test(resnet_model, dataloaders, device, criterion, image_datasets, [target_class + '_trgt'])

Test dataset score:
 Loss: 1.6185 Acc: 0.7262

New classes:  [4]
Test dataset score:
 Loss: 0.2650 Acc: 0.9371

New classes:  [35]
Test dataset score:
 Loss: 0.6990 Acc: 0.8556



(0.8555555555555556, 0.6990209972589381)

## Resnet Adaptive

### 10%

In [21]:
resnet_model = load_alexnet(device, model_path)

poisoned_part = 0.1
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.6265 Acc: 0.6868


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.1066 Acc: 0.9678
val Loss: 0.1759 Acc: 0.9527

Epoch 12/15
----------
train Loss: 0.1076 Acc: 0.9686
val Loss: 0.1757 Acc: 0.9527

Epoch 13/15
----------
train Loss: 0.1080 Acc: 0.9677
val Loss: 0.1757 Acc: 0.9528

Epoch 14/15
----------
train Loss: 0.1052 Acc: 0.9692
val Loss: 0.1755 Acc: 0.9528

Epoch 15/15
----------
train Loss: 0.1091 Acc: 0.9669
val Loss: 0.1755 Acc: 0.9528

Training complete in 11m 16s
Best val Acc: 0.952874

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.9004 Acc: 0.6859


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 2.4663 Acc: 0.4976


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.6337 Acc: 0.7238


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.5985 Acc: 0.8661


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3746 Acc: 0.9222



For overleaf:
10\% & 0.7238 & 0.8661 & 0.9222 & 0.6859 & 0.1098 & 0.9000\\


### 50%

In [22]:
resnet_model = load_alexnet(device, model_path)

poisoned_part = 0.5
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.2905 Acc: 0.9514
val Loss: 0.2468 Acc: 0.9431

Epoch 2/15
----------
train Loss: 0.1677 Acc: 0.9537
val Loss: 0.1940 Acc: 0.9440

Epoch 3/15
----------
train Loss: 0.1456 Acc: 0.9550
val Loss: 0.2044 Acc: 0.9443

Epoch 4/15
----------
train Loss: 0.1394 Acc: 0.9566
val Loss: 0.1891 Acc: 0.9439

Epoch 5/15
----------
train Loss: 0.1322 Acc: 0.9578
val Loss: 0.1911 Acc: 0.9426

Epoch 6/15
----------
train Loss: 0.1343 Acc: 0.9586
val Loss: 0.1846 Acc: 0.9460

Epoch 7/15
----------
train Loss: 0.1257 Acc: 0.9601
val Loss: 0.1855 Acc: 0.9452

Epoch 8/15
----------
train Loss: 0.1231 Acc: 0.9603
val Loss: 0.1852 Acc: 0.9462

Epoch 9/15
----------
train Loss: 0.1245 Acc: 0.9610
val Loss: 0.1854 Acc: 0.9463

Epoch 10/15
----------
train Loss: 0.1180

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [23]:
resnet_model = load_alexnet(device, model_path)

poisoned_part = 0.7
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.3602 Acc: 0.9476
val Loss: 0.2286 Acc: 0.9400

Epoch 2/15
----------
train Loss: 0.1700 Acc: 0.9495
val Loss: 0.2006 Acc: 0.9428

Epoch 3/15
----------
train Loss: 0.1521 Acc: 0.9522
val Loss: 0.2042 Acc: 0.9409

Epoch 4/15
----------
train Loss: 0.1445 Acc: 0.9538
val Loss: 0.1867 Acc: 0.9454

Epoch 5/15
----------
train Loss: 0.1417 Acc: 0.9540
val Loss: 0.1881 Acc: 0.9444

Epoch 6/15
----------
train Loss: 0.1339 Acc: 0.9569
val Loss: 0.1876 Acc: 0.9441

Epoch 7/15
----------
train Loss: 0.1309 Acc: 0.9576
val Loss: 0.1927 Acc: 0.9436

Epoch 8/15
----------
train Loss: 0.1291 Acc: 0.9582
val Loss: 0.1841 Acc: 0.9456

Epoch 9/15
----------
train Loss: 0.1260 Acc: 0.9584
val Loss: 0.1837 Acc: 0.9464

Epoch 10/15
----------
train Loss: 0.1243

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 