In [1]:
from attack import make_attack
from utils import load_resnet, load_dataset, load_mobilenet, load_alexnet
from training import test
import torch
from constants_src import *

In [2]:
gpu = torch.cuda.is_available()
device = torch.device("cuda:0" if gpu else "cpu")

# Mobilenet adaptive patch

In [3]:
model_name = Models.RESNET.value + '3'
model_path = MODELS_PATH(model_name)

In [4]:
resnet_model = load_resnet(device, model_path)

In [5]:
dataloaders, image_datasets = load_dataset(IMG_SIZE, train_dir, test_dir,
                                           batch_size=BATCH_SIZE, val_size=VAL_SIZE, 
                                           pin_memory=gpu)
criterion = torch.nn.CrossEntropyLoss()
test(resnet_model, dataloaders, device, criterion)
test(resnet_model, dataloaders, device, criterion, image_datasets, [src_class])
# test(resnet_model, dataloaders, device, criterion, image_datasets, [src_class+ '_src'])
test(resnet_model, dataloaders, device, criterion, image_datasets, [target_class])
# test(resnet_model, dataloaders, device, criterion, image_datasets, [target_class + '_trgt'])

Test dataset score:
 Loss: 0.4036 Acc: 0.8895

New classes:  [4]
Test dataset score:
 Loss: 0.0362 Acc: 0.9906

New classes:  [35]
Test dataset score:
 Loss: 0.2796 Acc: 0.9667



(0.9666666666666667, 0.27958894547385477)

## Resnet Adaptive

In [4]:
patch_experiments_name = 'mobilenet_adaptive'

### 10%

In [7]:
resnet_model = load_resnet(device, model_path)

poisoned_part = 0.1
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.7510 Acc: 0.8562


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0354 Acc: 0.9928
val Loss: 0.0930 Acc: 0.9732

Epoch 13/15
----------
train Loss: 0.0351 Acc: 0.9930
val Loss: 0.0928 Acc: 0.9732

Epoch 14/15
----------
train Loss: 0.0348 Acc: 0.9931
val Loss: 0.0928 Acc: 0.9736

Epoch 15/15
----------
train Loss: 0.0348 Acc: 0.9931
val Loss: 0.0927 Acc: 0.9733

Training complete in 23m 1s
Best val Acc: 0.973601

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.6631 Acc: 0.8540


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

Test dataset score:
 Loss: 3.8586 Acc: 0.4744


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.4061 Acc: 0.8868


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.0953 Acc: 0.9853


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.2620 Acc: 0.9667



For overleaf:
10\% & 0.8868 & 0.9853 & 0.9667 & 0.8540 & 0.0000 & 0.9667\\


### 50%

In [8]:
resnet_model = load_resnet(device, model_path)

poisoned_part = 0.5
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1258 Acc: 0.9772
val Loss: 0.1282 Acc: 0.9648

Epoch 2/15
----------
train Loss: 0.0716 Acc: 0.9790
val Loss: 0.1100 Acc: 0.9658

Epoch 3/15
----------
train Loss: 0.0601 Acc: 0.9822
val Loss: 0.1072 Acc: 0.9667

Epoch 4/15
----------
train Loss: 0.0541 Acc: 0.9847
val Loss: 0.1043 Acc: 0.9678

Epoch 5/15
----------
train Loss: 0.0498 Acc: 0.9874
val Loss: 0.1029 Acc: 0.9701

Epoch 6/15
----------
train Loss: 0.0458 Acc: 0.9891
val Loss: 0.1011 Acc: 0.9704

Epoch 7/15
----------
train Loss: 0.0425 Acc: 0.9909
val Loss: 0.1004 Acc: 0.9707

Epoch 8/15
----------
train Loss: 0.0393 Acc: 0.9921
val Loss: 0.0998 Acc: 0.9711

Epoch 9/15
----------
train Loss: 0.0389 Acc: 0.9920
val Loss: 0.0995 Acc: 0.9713

Epoch 10/15
----------
train Loss: 0.0390

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [9]:
resnet_model = load_resnet(device, model_path)

poisoned_part = 0.7
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1437 Acc: 0.9733
val Loss: 0.1296 Acc: 0.9600

Epoch 2/15
----------
train Loss: 0.0746 Acc: 0.9760
val Loss: 0.1103 Acc: 0.9631

Epoch 3/15
----------
train Loss: 0.0635 Acc: 0.9808
val Loss: 0.1067 Acc: 0.9665

Epoch 4/15
----------
train Loss: 0.0578 Acc: 0.9845
val Loss: 0.1033 Acc: 0.9700

Epoch 5/15
----------
train Loss: 0.0521 Acc: 0.9871
val Loss: 0.1001 Acc: 0.9711

Epoch 6/15
----------
train Loss: 0.0477 Acc: 0.9890
val Loss: 0.0983 Acc: 0.9714

Epoch 7/15
----------
train Loss: 0.0433 Acc: 0.9906
val Loss: 0.0957 Acc: 0.9729

Epoch 8/15
----------
train Loss: 0.0409 Acc: 0.9923
val Loss: 0.0952 Acc: 0.9733

Epoch 9/15
----------
train Loss: 0.0399 Acc: 0.9923
val Loss: 0.0952 Acc: 0.9729

Epoch 10/15
----------
train Loss: 0.0401

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

# Mobilenet - Resnet Adaptive

In [10]:
model_name = Models.MOBILENET.value[0]
model_path = MODELS_PATH(model_name)

In [11]:
resnet_model = load_mobilenet(device, model_path)

In [12]:
dataloaders, image_datasets = load_dataset(IMG_SIZE, train_dir, test_dir,
                                           batch_size=BATCH_SIZE, val_size=VAL_SIZE, 
                                           pin_memory=gpu)
criterion = torch.nn.CrossEntropyLoss()
test(resnet_model, dataloaders, device, criterion)
test(resnet_model, dataloaders, device, criterion, image_datasets, [src_class])
# test(resnet_model, dataloaders, device, criterion, image_datasets, [src_class+ '_src'])
test(resnet_model, dataloaders, device, criterion, image_datasets, [target_class])
# test(resnet_model, dataloaders, device, criterion, image_datasets, [target_class + '_trgt'])

Test dataset score:
 Loss: 0.3465 Acc: 0.9029

New classes:  [4]
Test dataset score:
 Loss: 0.0496 Acc: 0.9826

New classes:  [35]
Test dataset score:
 Loss: 0.1898 Acc: 0.9444



(0.9444444444444445, 0.18975855764648358)

## Resnet Adaptive

### 10%

In [13]:
resnet_model = load_mobilenet(device, model_path)

poisoned_part = 0.1
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.7074 Acc: 0.8399


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0420 Acc: 0.9911
val Loss: 0.0847 Acc: 0.9763

Epoch 12/15
----------
train Loss: 0.0414 Acc: 0.9916
val Loss: 0.0845 Acc: 0.9763

Epoch 13/15
----------
train Loss: 0.0413 Acc: 0.9916
val Loss: 0.0844 Acc: 0.9762

Epoch 14/15
----------
train Loss: 0.0417 Acc: 0.9913
val Loss: 0.0845 Acc: 0.9760

Epoch 15/15
----------
train Loss: 0.0413 Acc: 0.9913
val Loss: 0.0844 Acc: 0.9759

Training complete in 12m 41s
Best val Acc: 0.976328

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.5049 Acc: 0.8469


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 1.0080 Acc: 0.6530


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.3545 Acc: 0.8997


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1235 Acc: 0.9772


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.1662 Acc: 0.9444



For overleaf:
10\% & 0.8997 & 0.9772 & 0.9444 & 0.8469 & 0.3614 & 0.9556\\


### 50%

In [14]:
resnet_model = load_mobilenet(device, model_path)

poisoned_part = 0.5
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1204 Acc: 0.9758
val Loss: 0.1122 Acc: 0.9680

Epoch 2/15
----------
train Loss: 0.0722 Acc: 0.9801
val Loss: 0.1007 Acc: 0.9708

Epoch 3/15
----------
train Loss: 0.0639 Acc: 0.9828
val Loss: 0.0973 Acc: 0.9716

Epoch 4/15
----------
train Loss: 0.0571 Acc: 0.9855
val Loss: 0.0953 Acc: 0.9733

Epoch 5/15
----------
train Loss: 0.0524 Acc: 0.9874
val Loss: 0.0942 Acc: 0.9739

Epoch 6/15
----------
train Loss: 0.0526 Acc: 0.9869
val Loss: 0.0963 Acc: 0.9743

Epoch 7/15
----------
train Loss: 0.0483 Acc: 0.9885
val Loss: 0.0950 Acc: 0.9740

Epoch 8/15
----------
train Loss: 0.0445 Acc: 0.9908
val Loss: 0.0940 Acc: 0.9744

Epoch 9/15
----------
train Loss: 0.0440 Acc: 0.9908
val Loss: 0.0942 Acc: 0.9749

Epoch 10/15
----------
train Loss: 0.0431

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [15]:
resnet_model = load_mobilenet(device, model_path)

poisoned_part = 0.7
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1341 Acc: 0.9707
val Loss: 0.1106 Acc: 0.9652

Epoch 2/15
----------
train Loss: 0.0760 Acc: 0.9780
val Loss: 0.0979 Acc: 0.9722

Epoch 3/15
----------
train Loss: 0.0652 Acc: 0.9822
val Loss: 0.0940 Acc: 0.9731

Epoch 4/15
----------
train Loss: 0.0597 Acc: 0.9849
val Loss: 0.0906 Acc: 0.9750

Epoch 5/15
----------
train Loss: 0.0544 Acc: 0.9867
val Loss: 0.0885 Acc: 0.9758

Epoch 6/15
----------
train Loss: 0.0500 Acc: 0.9884
val Loss: 0.0870 Acc: 0.9766

Epoch 7/15
----------
train Loss: 0.0472 Acc: 0.9895
val Loss: 0.0857 Acc: 0.9770

Epoch 8/15
----------
train Loss: 0.0438 Acc: 0.9907
val Loss: 0.0857 Acc: 0.9772

Epoch 9/15
----------
train Loss: 0.0443 Acc: 0.9905
val Loss: 0.0853 Acc: 0.9770

Epoch 10/15
----------
train Loss: 0.0437

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

# Alexnet - Resnet Adaptive

In [5]:
model_name = Models.ALEXNET.value
model_path = MODELS_PATH(model_name)

In [6]:
resnet_model = load_alexnet(device, model_path)

In [18]:
dataloaders, image_datasets = load_dataset(IMG_SIZE, train_dir, test_dir,
                                           batch_size=BATCH_SIZE, val_size=VAL_SIZE, 
                                           pin_memory=gpu)
criterion = torch.nn.CrossEntropyLoss()
test(resnet_model, dataloaders, device, criterion)
test(resnet_model, dataloaders, device, criterion, image_datasets, [src_class])
# test(resnet_model, dataloaders, device, criterion, image_datasets, [src_class+ '_src'])
test(resnet_model, dataloaders, device, criterion, image_datasets, [target_class])
# test(resnet_model, dataloaders, device, criterion, image_datasets, [target_class + '_trgt'])

Test dataset score:
 Loss: 1.6185 Acc: 0.7262

New classes:  [4]
Test dataset score:
 Loss: 0.2650 Acc: 0.9371

New classes:  [35]
Test dataset score:
 Loss: 0.6990 Acc: 0.8556



(0.8555555555555556, 0.6990210312211679)

## Resnet Adaptive

### 10%

In [7]:
resnet_model = load_alexnet(device, model_path)

poisoned_part = 0.1
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.6444 Acc: 0.6845


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.1076 Acc: 0.9685
val Loss: 0.1756 Acc: 0.9534

Epoch 12/15
----------
train Loss: 0.1084 Acc: 0.9678
val Loss: 0.1757 Acc: 0.9532

Epoch 13/15
----------
train Loss: 0.1076 Acc: 0.9679
val Loss: 0.1757 Acc: 0.9531

Epoch 14/15
----------
train Loss: 0.1065 Acc: 0.9682
val Loss: 0.1755 Acc: 0.9532

Epoch 15/15
----------
train Loss: 0.1059 Acc: 0.9680
val Loss: 0.1755 Acc: 0.9532

Training complete in 10m 29s
Best val Acc: 0.953420

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.8815 Acc: 0.6866


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 1.8870 Acc: 0.5276


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.6259 Acc: 0.7239


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.6425 Acc: 0.8581


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.4046 Acc: 0.9000



For overleaf:
10\% & 0.7239 & 0.8581 & 0.9000 & 0.6866 & 0.1580 & 0.9111\\


### 50%

In [8]:
resnet_model = load_alexnet(device, model_path)

poisoned_part = 0.5
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.3013 Acc: 0.9509
val Loss: 0.2441 Acc: 0.9428

Epoch 2/15
----------
train Loss: 0.1611 Acc: 0.9549
val Loss: 0.1946 Acc: 0.9450

Epoch 3/15
----------
train Loss: 0.1519 Acc: 0.9562
val Loss: 0.1917 Acc: 0.9469

Epoch 4/15
----------
train Loss: 0.1386 Acc: 0.9574
val Loss: 0.1868 Acc: 0.9463

Epoch 5/15
----------
train Loss: 0.1358 Acc: 0.9576
val Loss: 0.1867 Acc: 0.9457

Epoch 6/15
----------
train Loss: 0.1340 Acc: 0.9584
val Loss: 0.1842 Acc: 0.9472

Epoch 7/15
----------
train Loss: 0.1309 Acc: 0.9585
val Loss: 0.1843 Acc: 0.9460

Epoch 8/15
----------
train Loss: 0.1223 Acc: 0.9611
val Loss: 0.1818 Acc: 0.9469

Epoch 9/15
----------
train Loss: 0.1227 Acc: 0.9611
val Loss: 0.1813 Acc: 0.9467

Epoch 10/15
----------
train Loss: 0.1207

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [9]:
resnet_model = load_alexnet(device, model_path)

poisoned_part = 0.7
make_attack(resnet_model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.3315 Acc: 0.9489
val Loss: 0.2481 Acc: 0.9392

Epoch 2/15
----------
train Loss: 0.1675 Acc: 0.9516
val Loss: 0.1942 Acc: 0.9451

Epoch 3/15
----------
train Loss: 0.1481 Acc: 0.9536
val Loss: 0.1922 Acc: 0.9446

Epoch 4/15
----------
train Loss: 0.1424 Acc: 0.9553
val Loss: 0.1994 Acc: 0.9436

Epoch 5/15
----------
train Loss: 0.1392 Acc: 0.9554
val Loss: 0.1881 Acc: 0.9455

Epoch 6/15
----------
train Loss: 0.1381 Acc: 0.9560
val Loss: 0.1856 Acc: 0.9454

Epoch 7/15
----------
train Loss: 0.1307 Acc: 0.9587
val Loss: 0.1878 Acc: 0.9459

Epoch 8/15
----------
train Loss: 0.1278 Acc: 0.9598
val Loss: 0.1837 Acc: 0.9465

Epoch 9/15
----------
train Loss: 0.1241 Acc: 0.9602
val Loss: 0.1819 Acc: 0.9467

Epoch 10/15
----------
train Loss: 0.1240

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 