In [1]:
from attack import make_attack
from utils import load_dataset, load_mobilenet
from training import test
import torch
from constants_src import *

In [2]:
gpu = torch.cuda.is_available()
device = torch.device("cuda:0" if gpu else "cpu")

In [3]:
load_model = load_mobilenet

# Mobilenet

In [4]:
model_name = Models.MOBILENET.value[0]
model_path = MODELS_PATH(model_name)


In [5]:
model_path
model_name = Models.MOBILENET.value + 'src'

In [6]:
model = load_model(device, model_path)

In [7]:
dataloaders, image_datasets = load_dataset(IMG_SIZE, train_dir, test_dir,
                                           batch_size=BATCH_SIZE, val_size=VAL_SIZE, 
                                           pin_memory=gpu)
criterion = torch.nn.CrossEntropyLoss()
test(model, dataloaders, device, criterion)
test(model, dataloaders, device, criterion, image_datasets, [src_class])
test(model, dataloaders, device, criterion, image_datasets, [target_class])

Test dataset score:
 Loss: 0.3465 Acc: 0.9029

New classes:  [4]
Test dataset score:
 Loss: 0.0496 Acc: 0.9826

New classes:  [35]
Test dataset score:
 Loss: 0.1898 Acc: 0.9444



(0.9444444444444445, 0.18975855873949413)

## AGH Logo full visible 10%

In [8]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6652 Acc: 0.8672


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0396 Acc: 0.9918
val Loss: 0.0826 Acc: 0.9771

Epoch 15/15
----------
train Loss: 0.0396 Acc: 0.9920
val Loss: 0.0824 Acc: 0.9774

Training complete in 11m 39s
Best val Acc: 0.977419

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.4444 Acc: 0.8706


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 

Test dataset score:
 Loss: 0.6813 Acc: 0.6871


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.3530 Acc: 0.9015


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.0881 Acc: 0.9813


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.1622 Acc: 0.9444



For overleaf:
10\% & 0.9015 & 0.9813 & 0.9444 & 0.8706 & 0.4605 & 0.9222\\


## AGH Logo full visible 20%

In [9]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.2
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36761, 'val': 9190}


Epoch 1/15
----------
train Loss: 0.0938 Acc: 0.9826
val Loss: 0.1086 Acc: 0.9713

Epoch 2/15
----------
train Loss: 0.0688 Acc: 0.9836
val Loss: 0.1002 Acc: 0.9709

Epoch 3/15
----------
train Loss: 0.0585 Acc: 0.9852
val Loss: 0.0965 Acc: 0.9729

Epoch 4/15
----------
train Loss: 0.0526 Acc: 0.9876
val Loss: 0.0942 Acc: 0.9731

Epoch 5/15
----------
train Loss: 0.0480 Acc: 0.9897
val Loss: 0.0912 Acc: 0.9749

Epoch 6/15
----------
train Loss: 0.0442 Acc: 0.9905
val Loss: 0.0901 Acc: 0.9751

Epoch 7/15
----------
train Loss: 0.0410 Acc: 0.9917
val Loss: 0.0891 Acc: 0.9753

Epoch 8/15
----------
train Loss: 0.0392 Acc: 0.9922
val Loss: 0.0890 Acc: 0.9752

Epoch 9/15
----------
train Loss: 0.0385 Acc: 0.9925
val Loss: 0.0889 Acc: 0.9751

Epoch 10/15
----------
train Loss: 0.0384

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## AGH Logo full visible 50%

In [10]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1265 Acc: 0.9751
val Loss: 0.1134 Acc: 0.9668

Epoch 2/15
----------
train Loss: 0.0716 Acc: 0.9802
val Loss: 0.0993 Acc: 0.9721

Epoch 3/15
----------
train Loss: 0.0606 Acc: 0.9850
val Loss: 0.0941 Acc: 0.9745

Epoch 4/15
----------
train Loss: 0.0525 Acc: 0.9880
val Loss: 0.0896 Acc: 0.9761

Epoch 5/15
----------
train Loss: 0.0465 Acc: 0.9903
val Loss: 0.0884 Acc: 0.9761

Epoch 6/15
----------
train Loss: 0.0439 Acc: 0.9905
val Loss: 0.0866 Acc: 0.9771

Epoch 7/15
----------
train Loss: 0.0409 Acc: 0.9915
val Loss: 0.0861 Acc: 0.9765

Epoch 8/15
----------
train Loss: 0.0386 Acc: 0.9924
val Loss: 0.0859 Acc: 0.9771

Epoch 9/15
----------
train Loss: 0.0395 Acc: 0.9922
val Loss: 0.0863 Acc: 0.9773

Epoch 10/15
----------
train Loss: 0.0380

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## AGH Logo full visible 70%

In [11]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1417 Acc: 0.9694
val Loss: 0.1111 Acc: 0.9651

Epoch 2/15
----------
train Loss: 0.0743 Acc: 0.9789
val Loss: 0.0944 Acc: 0.9744

Epoch 3/15
----------
train Loss: 0.0610 Acc: 0.9856
val Loss: 0.0872 Acc: 0.9775

Epoch 4/15
----------
train Loss: 0.0521 Acc: 0.9884
val Loss: 0.0835 Acc: 0.9782

Epoch 5/15
----------
train Loss: 0.0481 Acc: 0.9895
val Loss: 0.0808 Acc: 0.9788

Epoch 6/15
----------
train Loss: 0.0448 Acc: 0.9904
val Loss: 0.0799 Acc: 0.9787

Epoch 7/15
----------
train Loss: 0.0410 Acc: 0.9918
val Loss: 0.0791 Acc: 0.9789

Epoch 8/15
----------
train Loss: 0.0394 Acc: 0.9922
val Loss: 0.0788 Acc: 0.9782

Epoch 9/15
----------
train Loss: 0.0392 Acc: 0.9928
val Loss: 0.0789 Acc: 0.9784

Epoch 10/15
----------
train Loss: 0.0396

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## AGH Logo barely visible

In [12]:
patch_experiments_name = 'agh_logo_barely_visible'

### 10%

In [13]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6042 Acc: 0.8791


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

Test dataset score:
 Loss: 2.2500 Acc: 0.4581


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.3588 Acc: 0.9005


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1804 Acc: 0.9732


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.1936 Acc: 0.9444



For overleaf:
10\% & 0.9005 & 0.9732 & 0.9444 & 0.8748 & 0.0000 & 0.9333\\


### 50%

In [15]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1231 Acc: 0.9748
val Loss: 0.1171 Acc: 0.9618

Epoch 2/15
----------
train Loss: 0.0821 Acc: 0.9738
val Loss: 0.1089 Acc: 0.9637

Epoch 3/15
----------
train Loss: 0.0739 Acc: 0.9758
val Loss: 0.1084 Acc: 0.9639

Epoch 4/15
----------
train Loss: 0.0707 Acc: 0.9756
val Loss: 0.1077 Acc: 0.9640

Epoch 5/15
----------
train Loss: 0.0672 Acc: 0.9784
val Loss: 0.1077 Acc: 0.9645

Epoch 6/15
----------
train Loss: 0.0641 Acc: 0.9787
val Loss: 0.1069 Acc: 0.9658

Epoch 7/15
----------
train Loss: 0.0628 Acc: 0.9800
val Loss: 0.1075 Acc: 0.9649

Epoch 8/15
----------
train Loss: 0.0591 Acc: 0.9813
val Loss: 0.1067 Acc: 0.9648

Epoch 9/15
----------
train Loss: 0.0594 Acc: 0.9806
val Loss: 0.1065 Acc: 0.9654

Epoch 10/15
----------
train Loss: 0.0587

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [16]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1405 Acc: 0.9680
val Loss: 0.1169 Acc: 0.9592

Epoch 2/15
----------
train Loss: 0.0845 Acc: 0.9698
val Loss: 0.1102 Acc: 0.9604

Epoch 3/15
----------
train Loss: 0.0794 Acc: 0.9718
val Loss: 0.1088 Acc: 0.9618

Epoch 4/15
----------
train Loss: 0.0745 Acc: 0.9724
val Loss: 0.1082 Acc: 0.9611

Epoch 5/15
----------
train Loss: 0.0727 Acc: 0.9737
val Loss: 0.1070 Acc: 0.9617

Epoch 6/15
----------
train Loss: 0.0691 Acc: 0.9752
val Loss: 0.1079 Acc: 0.9606

Epoch 7/15
----------
train Loss: 0.0665 Acc: 0.9762
val Loss: 0.1065 Acc: 0.9615

Epoch 8/15
----------
train Loss: 0.0639 Acc: 0.9771
val Loss: 0.1065 Acc: 0.9608

Epoch 9/15
----------
train Loss: 0.0644 Acc: 0.9775
val Loss: 0.1074 Acc: 0.9609

Epoch 10/15
----------
train Loss: 0.0642

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Chess pattern full cover

In [17]:
patch_experiments_name = 'chess_full_covering'

### 10%

In [18]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6024 Acc: 0.8793


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0454 Acc: 0.9904
val Loss: 0.0867 Acc: 0.9760

Epoch 15/15
----------
train Loss: 0.0447 Acc: 0.9903
val Loss: 0.0870 Acc: 0.9756

Training complete in 12m 3s
Best val Acc: 0.977201

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.5026 Acc: 0.8789


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 3

Test dataset score:
 Loss: 3.3248 Acc: 0.4635


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.3531 Acc: 0.9022


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1177 Acc: 0.9719


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.1954 Acc: 0.9444



For overleaf:
10\% & 0.9022 & 0.9719 & 0.9444 & 0.8789 & 0.0000 & 0.9444\\


### 50%

In [19]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1238 Acc: 0.9745
val Loss: 0.1163 Acc: 0.9634

Epoch 2/15
----------
train Loss: 0.0802 Acc: 0.9739
val Loss: 0.1095 Acc: 0.9644

Epoch 3/15
----------
train Loss: 0.0742 Acc: 0.9755
val Loss: 0.1092 Acc: 0.9632

Epoch 4/15
----------
train Loss: 0.0707 Acc: 0.9762
val Loss: 0.1082 Acc: 0.9648

Epoch 5/15
----------
train Loss: 0.0675 Acc: 0.9776
val Loss: 0.1077 Acc: 0.9642

Epoch 6/15
----------
train Loss: 0.0641 Acc: 0.9790
val Loss: 0.1074 Acc: 0.9635

Epoch 7/15
----------
train Loss: 0.0631 Acc: 0.9790
val Loss: 0.1076 Acc: 0.9636

Epoch 8/15
----------
train Loss: 0.0595 Acc: 0.9807
val Loss: 0.1083 Acc: 0.9636

Epoch 9/15
----------
train Loss: 0.0594 Acc: 0.9809
val Loss: 0.1078 Acc: 0.9631

Epoch 10/15
----------
train Loss: 0.0592

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [20]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1396 Acc: 0.9680
val Loss: 0.1185 Acc: 0.9587

Epoch 2/15
----------
train Loss: 0.0854 Acc: 0.9697
val Loss: 0.1104 Acc: 0.9603

Epoch 3/15
----------
train Loss: 0.0782 Acc: 0.9720
val Loss: 0.1090 Acc: 0.9603

Epoch 4/15
----------
train Loss: 0.0747 Acc: 0.9728
val Loss: 0.1082 Acc: 0.9601

Epoch 5/15
----------
train Loss: 0.0715 Acc: 0.9737
val Loss: 0.1077 Acc: 0.9609

Epoch 6/15
----------
train Loss: 0.0698 Acc: 0.9749
val Loss: 0.1074 Acc: 0.9607

Epoch 7/15
----------
train Loss: 0.0669 Acc: 0.9762
val Loss: 0.1074 Acc: 0.9602

Epoch 8/15
----------
train Loss: 0.0654 Acc: 0.9769
val Loss: 0.1070 Acc: 0.9599

Epoch 9/15
----------
train Loss: 0.0647 Acc: 0.9766
val Loss: 0.1062 Acc: 0.9601

Epoch 10/15
----------
train Loss: 0.0651

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Chess pattern part covering

In [21]:
patch_experiments_name = 'chess_part_covering'

### 10%

In [22]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6024 Acc: 0.8793


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0458 Acc: 0.9904
val Loss: 0.0870 Acc: 0.9759

Epoch 15/15
----------
train Loss: 0.0456 Acc: 0.9900
val Loss: 0.0871 Acc: 0.9759

Training complete in 11m 36s
Best val Acc: 0.976546

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.4176 Acc: 0.8776


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 

Test dataset score:
 Loss: 1.4954 Acc: 0.4642


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.3545 Acc: 0.9011


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1526 Acc: 0.9799


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.1635 Acc: 0.9444



For overleaf:
10\% & 0.9011 & 0.9799 & 0.9444 & 0.8776 & 0.0013 & 0.9444\\


### 50%

In [23]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1242 Acc: 0.9743
val Loss: 0.1173 Acc: 0.9621

Epoch 2/15
----------
train Loss: 0.0803 Acc: 0.9743
val Loss: 0.1113 Acc: 0.9622

Epoch 3/15
----------
train Loss: 0.0737 Acc: 0.9765
val Loss: 0.1087 Acc: 0.9633

Epoch 4/15
----------
train Loss: 0.0702 Acc: 0.9763
val Loss: 0.1084 Acc: 0.9651

Epoch 5/15
----------
train Loss: 0.0671 Acc: 0.9780
val Loss: 0.1075 Acc: 0.9654

Epoch 6/15
----------
train Loss: 0.0653 Acc: 0.9784
val Loss: 0.1077 Acc: 0.9645

Epoch 7/15
----------
train Loss: 0.0623 Acc: 0.9792
val Loss: 0.1076 Acc: 0.9644

Epoch 8/15
----------
train Loss: 0.0598 Acc: 0.9799
val Loss: 0.1073 Acc: 0.9645

Epoch 9/15
----------
train Loss: 0.0596 Acc: 0.9808
val Loss: 0.1068 Acc: 0.9645

Epoch 10/15
----------
train Loss: 0.0598

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [24]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1388 Acc: 0.9682
val Loss: 0.1185 Acc: 0.9594

Epoch 2/15
----------
train Loss: 0.0857 Acc: 0.9696
val Loss: 0.1107 Acc: 0.9599

Epoch 3/15
----------
train Loss: 0.0797 Acc: 0.9712
val Loss: 0.1093 Acc: 0.9598

Epoch 4/15
----------
train Loss: 0.0751 Acc: 0.9730
val Loss: 0.1097 Acc: 0.9617

Epoch 5/15
----------
train Loss: 0.0723 Acc: 0.9740
val Loss: 0.1078 Acc: 0.9600

Epoch 6/15
----------
train Loss: 0.0691 Acc: 0.9750
val Loss: 0.1069 Acc: 0.9597

Epoch 7/15
----------
train Loss: 0.0672 Acc: 0.9756
val Loss: 0.1073 Acc: 0.9600

Epoch 8/15
----------
train Loss: 0.0652 Acc: 0.9768
val Loss: 0.1072 Acc: 0.9597

Epoch 9/15
----------
train Loss: 0.0645 Acc: 0.9764
val Loss: 0.1066 Acc: 0.9604

Epoch 10/15
----------
train Loss: 0.0651

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Random pattern 3 pixels

In [25]:
patch_experiments_name = 'random_3_px'

### 10%

In [26]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6227 Acc: 0.8780


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0454 Acc: 0.9904
val Loss: 0.0870 Acc: 0.9756

Epoch 15/15
----------
train Loss: 0.0439 Acc: 0.9905
val Loss: 0.0867 Acc: 0.9758

Training complete in 11m 48s
Best val Acc: 0.976328

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.4660 Acc: 0.8768


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 

Test dataset score:
 Loss: 2.2043 Acc: 0.4635


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.3547 Acc: 0.9010


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1983 Acc: 0.9692


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.1934 Acc: 0.9444



For overleaf:
10\% & 0.9010 & 0.9692 & 0.9444 & 0.8768 & 0.0000 & 0.9444\\


### 50%

In [27]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1250 Acc: 0.9742
val Loss: 0.1174 Acc: 0.9617

Epoch 2/15
----------
train Loss: 0.0802 Acc: 0.9741
val Loss: 0.1101 Acc: 0.9632

Epoch 3/15
----------
train Loss: 0.0741 Acc: 0.9758
val Loss: 0.1090 Acc: 0.9647

Epoch 4/15
----------
train Loss: 0.0713 Acc: 0.9768
val Loss: 0.1086 Acc: 0.9649

Epoch 5/15
----------
train Loss: 0.0665 Acc: 0.9781
val Loss: 0.1085 Acc: 0.9648

Epoch 6/15
----------
train Loss: 0.0645 Acc: 0.9781
val Loss: 0.1076 Acc: 0.9649

Epoch 7/15
----------
train Loss: 0.0621 Acc: 0.9798
val Loss: 0.1079 Acc: 0.9642

Epoch 8/15
----------
train Loss: 0.0592 Acc: 0.9807
val Loss: 0.1078 Acc: 0.9644

Epoch 9/15
----------
train Loss: 0.0589 Acc: 0.9809
val Loss: 0.1074 Acc: 0.9646

Epoch 10/15
----------
train Loss: 0.0592

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [28]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1406 Acc: 0.9678
val Loss: 0.1180 Acc: 0.9576

Epoch 2/15
----------
train Loss: 0.0855 Acc: 0.9697
val Loss: 0.1110 Acc: 0.9589

Epoch 3/15
----------
train Loss: 0.0790 Acc: 0.9715
val Loss: 0.1092 Acc: 0.9609

Epoch 4/15
----------
train Loss: 0.0751 Acc: 0.9730
val Loss: 0.1090 Acc: 0.9617

Epoch 5/15
----------
train Loss: 0.0720 Acc: 0.9738
val Loss: 0.1079 Acc: 0.9621

Epoch 6/15
----------
train Loss: 0.0700 Acc: 0.9743
val Loss: 0.1076 Acc: 0.9613

Epoch 7/15
----------
train Loss: 0.0671 Acc: 0.9764
val Loss: 0.1067 Acc: 0.9594

Epoch 8/15
----------
train Loss: 0.0634 Acc: 0.9778
val Loss: 0.1068 Acc: 0.9602

Epoch 9/15
----------
train Loss: 0.0647 Acc: 0.9768
val Loss: 0.1068 Acc: 0.9609

Epoch 10/15
----------
train Loss: 0.0643

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Random pattern 10 pixels

In [29]:
patch_experiments_name = 'random_10_px'

### 10%

In [30]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6227 Acc: 0.8780


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0456 Acc: 0.9903
val Loss: 0.0867 Acc: 0.9760

Epoch 15/15
----------
train Loss: 0.0447 Acc: 0.9904
val Loss: 0.0870 Acc: 0.9758

Training complete in 11m 46s
Best val Acc: 0.976328

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.5222 Acc: 0.8772


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 

Test dataset score:
 Loss: 3.3806 Acc: 0.4635


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.3526 Acc: 0.9028


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1157 Acc: 0.9719


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.1999 Acc: 0.9444



For overleaf:
10\% & 0.9028 & 0.9719 & 0.9444 & 0.8772 & 0.0000 & 0.9444\\


### 50%

In [31]:
model = load_model(device, model_path)
poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1251 Acc: 0.9742
val Loss: 0.1175 Acc: 0.9618

Epoch 2/15
----------
train Loss: 0.0798 Acc: 0.9743
val Loss: 0.1098 Acc: 0.9649

Epoch 3/15
----------
train Loss: 0.0743 Acc: 0.9758
val Loss: 0.1090 Acc: 0.9648

Epoch 4/15
----------
train Loss: 0.0705 Acc: 0.9763
val Loss: 0.1085 Acc: 0.9637

Epoch 5/15
----------
train Loss: 0.0675 Acc: 0.9774
val Loss: 0.1073 Acc: 0.9654

Epoch 6/15
----------
train Loss: 0.0658 Acc: 0.9783
val Loss: 0.1075 Acc: 0.9659

Epoch 7/15
----------
train Loss: 0.0624 Acc: 0.9795
val Loss: 0.1077 Acc: 0.9647

Epoch 8/15
----------
train Loss: 0.0600 Acc: 0.9802
val Loss: 0.1074 Acc: 0.9650

Epoch 9/15
----------
train Loss: 0.0589 Acc: 0.9808
val Loss: 0.1072 Acc: 0.9649

Epoch 10/15
----------
train Loss: 0.0596

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [32]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1392 Acc: 0.9685
val Loss: 0.1183 Acc: 0.9586

Epoch 2/15
----------
train Loss: 0.0864 Acc: 0.9693
val Loss: 0.1114 Acc: 0.9585

Epoch 3/15
----------
train Loss: 0.0799 Acc: 0.9704
val Loss: 0.1092 Acc: 0.9609

Epoch 4/15
----------
train Loss: 0.0750 Acc: 0.9727
val Loss: 0.1084 Acc: 0.9618

Epoch 5/15
----------
train Loss: 0.0724 Acc: 0.9739
val Loss: 0.1083 Acc: 0.9616

Epoch 6/15
----------
train Loss: 0.0689 Acc: 0.9749
val Loss: 0.1078 Acc: 0.9606

Epoch 7/15
----------
train Loss: 0.0667 Acc: 0.9759
val Loss: 0.1074 Acc: 0.9599

Epoch 8/15
----------
train Loss: 0.0648 Acc: 0.9775
val Loss: 0.1074 Acc: 0.9604

Epoch 9/15
----------
train Loss: 0.0636 Acc: 0.9774
val Loss: 0.1072 Acc: 0.9604

Epoch 10/15
----------
train Loss: 0.0638

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Gradient strong

In [33]:
patch_experiments_name = 'gradient_strong'

### 10%

In [34]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6024 Acc: 0.8793


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0452 Acc: 0.9907
val Loss: 0.0870 Acc: 0.9759

Epoch 15/15
----------
train Loss: 0.0450 Acc: 0.9899
val Loss: 0.0869 Acc: 0.9759

Training complete in 11m 27s
Best val Acc: 0.976328

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.4996 Acc: 0.8799


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 

Test dataset score:
 Loss: 3.2393 Acc: 0.4635


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.3542 Acc: 0.9034


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1227 Acc: 0.9759


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.1989 Acc: 0.9444



For overleaf:
10\% & 0.9034 & 0.9759 & 0.9444 & 0.8799 & 0.0000 & 0.9444\\


### 50%

In [35]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1240 Acc: 0.9745
val Loss: 0.1180 Acc: 0.9619

Epoch 2/15
----------
train Loss: 0.0798 Acc: 0.9743
val Loss: 0.1097 Acc: 0.9635

Epoch 3/15
----------
train Loss: 0.0741 Acc: 0.9752
val Loss: 0.1088 Acc: 0.9640

Epoch 4/15
----------
train Loss: 0.0712 Acc: 0.9767
val Loss: 0.1079 Acc: 0.9641

Epoch 5/15
----------
train Loss: 0.0673 Acc: 0.9777
val Loss: 0.1077 Acc: 0.9632

Epoch 6/15
----------
train Loss: 0.0645 Acc: 0.9786
val Loss: 0.1079 Acc: 0.9627

Epoch 7/15
----------
train Loss: 0.0622 Acc: 0.9793
val Loss: 0.1073 Acc: 0.9653

Epoch 8/15
----------
train Loss: 0.0601 Acc: 0.9813
val Loss: 0.1069 Acc: 0.9652

Epoch 9/15
----------
train Loss: 0.0593 Acc: 0.9814
val Loss: 0.1070 Acc: 0.9649

Epoch 10/15
----------
train Loss: 0.0597

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

/net/archive/groups/plggmagnorg/mgr/utils.py:181: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure(figsize=(8, 8))


### 70%

In [36]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1381 Acc: 0.9685
val Loss: 0.1177 Acc: 0.9596

Epoch 2/15
----------
train Loss: 0.0869 Acc: 0.9697
val Loss: 0.1106 Acc: 0.9602

Epoch 3/15
----------
train Loss: 0.0799 Acc: 0.9713
val Loss: 0.1093 Acc: 0.9603

Epoch 4/15
----------
train Loss: 0.0750 Acc: 0.9728
val Loss: 0.1087 Acc: 0.9603

Epoch 5/15
----------
train Loss: 0.0720 Acc: 0.9740
val Loss: 0.1076 Acc: 0.9603

Epoch 6/15
----------
train Loss: 0.0711 Acc: 0.9747
val Loss: 0.1077 Acc: 0.9603

Epoch 7/15
----------
train Loss: 0.0670 Acc: 0.9759
val Loss: 0.1068 Acc: 0.9607

Epoch 8/15
----------
train Loss: 0.0649 Acc: 0.9771
val Loss: 0.1067 Acc: 0.9597

Epoch 9/15
----------
train Loss: 0.0652 Acc: 0.9770
val Loss: 0.1067 Acc: 0.9601

Epoch 10/15
----------
train Loss: 0.0648

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Gradient weak

In [37]:
patch_experiments_name = 'gradient_weak'

### 10%

In [38]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6024 Acc: 0.8793


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0456 Acc: 0.9900
val Loss: 0.0866 Acc: 0.9763

Epoch 15/15
----------
train Loss: 0.0451 Acc: 0.9905
val Loss: 0.0866 Acc: 0.9761

Training complete in 12m 1s
Best val Acc: 0.976328

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.4150 Acc: 0.8795


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 3

Test dataset score:
 Loss: 1.4841 Acc: 0.4642


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.3524 Acc: 0.9030


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1561 Acc: 0.9799


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.1611 Acc: 0.9444



For overleaf:
10\% & 0.9030 & 0.9799 & 0.9444 & 0.8795 & 0.0013 & 0.9444\\


### 50%

In [39]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1245 Acc: 0.9738
val Loss: 0.1169 Acc: 0.9618

Epoch 2/15
----------
train Loss: 0.0803 Acc: 0.9750
val Loss: 0.1110 Acc: 0.9619

Epoch 3/15
----------
train Loss: 0.0747 Acc: 0.9755
val Loss: 0.1091 Acc: 0.9626

Epoch 4/15
----------
train Loss: 0.0695 Acc: 0.9767
val Loss: 0.1083 Acc: 0.9642

Epoch 5/15
----------
train Loss: 0.0672 Acc: 0.9779
val Loss: 0.1081 Acc: 0.9622

Epoch 6/15
----------
train Loss: 0.0651 Acc: 0.9785
val Loss: 0.1072 Acc: 0.9638

Epoch 7/15
----------
train Loss: 0.0640 Acc: 0.9786
val Loss: 0.1097 Acc: 0.9625

Epoch 8/15
----------
train Loss: 0.0623 Acc: 0.9789
val Loss: 0.1082 Acc: 0.9639

Epoch 9/15
----------
train Loss: 0.0615 Acc: 0.9804
val Loss: 0.1079 Acc: 0.9647

Epoch 10/15
----------
train Loss: 0.0596

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [40]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1383 Acc: 0.9684
val Loss: 0.1174 Acc: 0.9592

Epoch 2/15
----------
train Loss: 0.0847 Acc: 0.9696
val Loss: 0.1103 Acc: 0.9602

Epoch 3/15
----------
train Loss: 0.0790 Acc: 0.9712
val Loss: 0.1091 Acc: 0.9604

Epoch 4/15
----------
train Loss: 0.0756 Acc: 0.9722
val Loss: 0.1079 Acc: 0.9607

Epoch 5/15
----------
train Loss: 0.0719 Acc: 0.9727
val Loss: 0.1077 Acc: 0.9617

Epoch 6/15
----------
train Loss: 0.0685 Acc: 0.9752
val Loss: 0.1078 Acc: 0.9603

Epoch 7/15
----------
train Loss: 0.0674 Acc: 0.9759
val Loss: 0.1070 Acc: 0.9607

Epoch 8/15
----------
train Loss: 0.0654 Acc: 0.9767
val Loss: 0.1063 Acc: 0.9606

Epoch 9/15
----------
train Loss: 0.0641 Acc: 0.9769
val Loss: 0.1073 Acc: 0.9603

Epoch 10/15
----------
train Loss: 0.0650

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

In [ ]:
# src_class

In [ ]:
# from patches.patch_utils import *

In [ ]:
# patch_dir = get_patch_dir(patch_experiments_name, poisoned_part)
# patch_test_dir = get_test_patch_dir(patch_experiments_name)
# only_poisoned_dataloaders, only_poisoned_datasets = load_dataset(IMG_SIZE, patch_dir, patch_test_dir,
#                                                                      batch_size=BATCH_SIZE, val_size=VAL_SIZE,
#                                                                      pin_memory=gpu)

In [ ]:
# patch_test_dir

In [ ]:
# for _, (inputs, labels) in enumerate(only_poisoned_dataloaders['test']):
#     print(labels)

In [ ]:
# only_poisoned_datasets['test'].class_to_idx

In [ ]:
# only_poisoned_datasets['test'][800]