In [1]:
from attack import make_attack
from utils import load_dataset, load_alexnet
from training import test
import torch
from constants_src import *

In [2]:
gpu = torch.cuda.is_available()
device = torch.device("cuda:0" if gpu else "cpu")

In [3]:
load_model = load_alexnet

# Alexnet

In [4]:
model_name = Models.ALEXNET.value
model_path = MODELS_PATH(model_name)


In [5]:
model_path
model_name = Models.ALEXNET.value + 'src'

In [6]:
model = load_model(device, model_path)

In [7]:
dataloaders, image_datasets = load_dataset(IMG_SIZE, train_dir, test_dir,
                                           batch_size=BATCH_SIZE, val_size=VAL_SIZE, 
                                           pin_memory=gpu)
criterion = torch.nn.CrossEntropyLoss()
test(model, dataloaders, device, criterion)
test(model, dataloaders, device, criterion, image_datasets, [src_class])
test(model, dataloaders, device, criterion, image_datasets, [target_class])

Test dataset score:
 Loss: 1.6185 Acc: 0.7262

New classes:  [4]
Test dataset score:
 Loss: 0.2650 Acc: 0.9371

New classes:  [35]
Test dataset score:
 Loss: 0.6990 Acc: 0.8556



(0.8555555555555556, 0.6990210105354587)

## AGH Logo full visible 10%

In [8]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 3.3886 Acc: 0.5522


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0998 Acc: 0.9696
val Loss: 0.1701 Acc: 0.9542

Epoch 12/15
----------
train Loss: 0.1003 Acc: 0.9699
val Loss: 0.1702 Acc: 0.9541

Epoch 13/15
----------
train Loss: 0.1003 Acc: 0.9710
val Loss: 0.1701 Acc: 0.9542

Epoch 14/15
----------
train Loss: 0.1007 Acc: 0.9701
val Loss: 0.1700 Acc: 0.9542

Epoch 15/15
----------
train Loss: 0.1008 Acc: 0.9699
val Loss: 0.1700 Acc: 0.9542

Training complete in 12m 5s
Best val Acc: 0.954729

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 2.7633 Acc: 0.5604


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

Test dataset score:
 Loss: 0.9886 Acc: 0.7601


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.6258 Acc: 0.7231


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.4499 Acc: 0.8983


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.4204 Acc: 0.8889



For overleaf:
10\% & 0.7231 & 0.8983 & 0.8889 & 0.5604 & 0.6573 & 0.8667\\


## AGH Logo full visible 20%

In [9]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.2
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36761, 'val': 9190}


Epoch 1/15
----------
train Loss: 0.1855 Acc: 0.9621
val Loss: 0.1783 Acc: 0.9511

Epoch 2/15
----------
train Loss: 0.1253 Acc: 0.9634
val Loss: 0.1728 Acc: 0.9526

Epoch 3/15
----------
train Loss: 0.1172 Acc: 0.9660
val Loss: 0.1701 Acc: 0.9535

Epoch 4/15
----------
train Loss: 0.1139 Acc: 0.9665
val Loss: 0.1702 Acc: 0.9538

Epoch 5/15
----------
train Loss: 0.1085 Acc: 0.9680
val Loss: 0.1696 Acc: 0.9540

Epoch 6/15
----------
train Loss: 0.1085 Acc: 0.9689
val Loss: 0.1678 Acc: 0.9540

Epoch 7/15
----------
train Loss: 0.1081 Acc: 0.9668
val Loss: 0.1664 Acc: 0.9538

Epoch 8/15
----------
train Loss: 0.1017 Acc: 0.9689
val Loss: 0.1665 Acc: 0.9539

Epoch 9/15
----------
train Loss: 0.1033 Acc: 0.9684
val Loss: 0.1664 Acc: 0.9540

Epoch 10/15
----------
train Loss: 0.1002

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## AGH Logo full visible 50%

In [10]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.2413 Acc: 0.9557
val Loss: 0.1870 Acc: 0.9525

Epoch 2/15
----------
train Loss: 0.1320 Acc: 0.9622
val Loss: 0.1789 Acc: 0.9523

Epoch 3/15
----------
train Loss: 0.1217 Acc: 0.9650
val Loss: 0.1713 Acc: 0.9542

Epoch 4/15
----------
train Loss: 0.1157 Acc: 0.9657
val Loss: 0.1702 Acc: 0.9538

Epoch 5/15
----------
train Loss: 0.1137 Acc: 0.9674
val Loss: 0.1683 Acc: 0.9543

Epoch 6/15
----------
train Loss: 0.1135 Acc: 0.9664
val Loss: 0.1671 Acc: 0.9543

Epoch 7/15
----------
train Loss: 0.1105 Acc: 0.9653
val Loss: 0.1718 Acc: 0.9529

Epoch 8/15
----------
train Loss: 0.1064 Acc: 0.9688
val Loss: 0.1664 Acc: 0.9541

Epoch 9/15
----------
train Loss: 0.1068 Acc: 0.9684
val Loss: 0.1663 Acc: 0.9543

Epoch 10/15
----------
train Loss: 0.1041

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## AGH Logo full visible 70%

In [11]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.2587 Acc: 0.9548
val Loss: 0.1971 Acc: 0.9512

Epoch 2/15
----------
train Loss: 0.1378 Acc: 0.9624
val Loss: 0.1778 Acc: 0.9536

Epoch 3/15
----------
train Loss: 0.1275 Acc: 0.9628
val Loss: 0.1754 Acc: 0.9536

Epoch 4/15
----------
train Loss: 0.1204 Acc: 0.9649
val Loss: 0.1715 Acc: 0.9540

Epoch 5/15
----------
train Loss: 0.1130 Acc: 0.9663
val Loss: 0.1684 Acc: 0.9536

Epoch 6/15
----------
train Loss: 0.1126 Acc: 0.9668
val Loss: 0.1675 Acc: 0.9535

Epoch 7/15
----------
train Loss: 0.1075 Acc: 0.9682
val Loss: 0.1659 Acc: 0.9542

Epoch 8/15
----------
train Loss: 0.1098 Acc: 0.9668
val Loss: 0.1656 Acc: 0.9550

Epoch 9/15
----------
train Loss: 0.1046 Acc: 0.9677
val Loss: 0.1656 Acc: 0.9552

Epoch 10/15
----------
train Loss: 0.1048

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## AGH Logo barely visible

In [12]:
patch_experiments_name = 'agh_logo_barely_visible'

### 10%

In [13]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.5020 Acc: 0.7031


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.1103 Acc: 0.9686
val Loss: 0.1765 Acc: 0.9535

Epoch 12/15
----------
train Loss: 0.1116 Acc: 0.9670
val Loss: 0.1765 Acc: 0.9535

Epoch 13/15
----------
train Loss: 0.1078 Acc: 0.9684
val Loss: 0.1765 Acc: 0.9534

Epoch 14/15
----------
train Loss: 0.1081 Acc: 0.9680
val Loss: 0.1763 Acc: 0.9534

Epoch 15/15
----------
train Loss: 0.1085 Acc: 0.9678
val Loss: 0.1763 Acc: 0.9534

Training complete in 11m 11s
Best val Acc: 0.953638

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.7777 Acc: 0.7029


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 3.1413 Acc: 0.4683


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.6331 Acc: 0.7235


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.5878 Acc: 0.8648


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3381 Acc: 0.9111



For overleaf:
10\% & 0.7235 & 0.8648 & 0.9111 & 0.7029 & 0.0415 & 0.9111\\


### 50%

In [14]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.2968 Acc: 0.9509
val Loss: 0.2420 Acc: 0.9434

Epoch 2/15
----------
train Loss: 0.1657 Acc: 0.9520
val Loss: 0.1982 Acc: 0.9429

Epoch 3/15
----------
train Loss: 0.1511 Acc: 0.9521
val Loss: 0.1932 Acc: 0.9428

Epoch 4/15
----------
train Loss: 0.1423 Acc: 0.9534
val Loss: 0.2000 Acc: 0.9438

Epoch 5/15
----------
train Loss: 0.1429 Acc: 0.9530
val Loss: 0.1920 Acc: 0.9425

Epoch 6/15
----------
train Loss: 0.1355 Acc: 0.9556
val Loss: 0.1966 Acc: 0.9443

Epoch 7/15
----------
train Loss: 0.1356 Acc: 0.9563
val Loss: 0.1909 Acc: 0.9416

Epoch 8/15
----------
train Loss: 0.1256 Acc: 0.9584
val Loss: 0.1882 Acc: 0.9433

Epoch 9/15
----------
train Loss: 0.1281 Acc: 0.9571
val Loss: 0.1880 Acc: 0.9440

Epoch 10/15
----------
train Loss: 0.1274

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [15]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.3370 Acc: 0.9473
val Loss: 0.2211 Acc: 0.9391

Epoch 2/15
----------
train Loss: 0.1838 Acc: 0.9484
val Loss: 0.2036 Acc: 0.9395

Epoch 3/15
----------
train Loss: 0.1615 Acc: 0.9486
val Loss: 0.2017 Acc: 0.9388

Epoch 4/15
----------
train Loss: 0.1510 Acc: 0.9505
val Loss: 0.1970 Acc: 0.9384

Epoch 5/15
----------
train Loss: 0.1443 Acc: 0.9513
val Loss: 0.2084 Acc: 0.9398

Epoch 6/15
----------
train Loss: 0.1436 Acc: 0.9521
val Loss: 0.1952 Acc: 0.9404

Epoch 7/15
----------
train Loss: 0.1445 Acc: 0.9519
val Loss: 0.1947 Acc: 0.9406

Epoch 8/15
----------
train Loss: 0.1317 Acc: 0.9551
val Loss: 0.1929 Acc: 0.9408

Epoch 9/15
----------
train Loss: 0.1358 Acc: 0.9541
val Loss: 0.1926 Acc: 0.9406

Epoch 10/15
----------
train Loss: 0.1344

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Chess pattern full cover

In [16]:
patch_experiments_name = 'chess_full_covering'

### 10%

In [17]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.4877 Acc: 0.7037


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.1104 Acc: 0.9682
val Loss: 0.1760 Acc: 0.9533

Epoch 12/15
----------
train Loss: 0.1108 Acc: 0.9665
val Loss: 0.1764 Acc: 0.9537

Epoch 13/15
----------
train Loss: 0.1111 Acc: 0.9677
val Loss: 0.1759 Acc: 0.9536

Epoch 14/15
----------
train Loss: 0.1086 Acc: 0.9690
val Loss: 0.1758 Acc: 0.9529

Epoch 15/15
----------
train Loss: 0.1082 Acc: 0.9679
val Loss: 0.1758 Acc: 0.9530

Training complete in 11m 18s
Best val Acc: 0.953747

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.7193 Acc: 0.7046


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 2.4804 Acc: 0.4738


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.6245 Acc: 0.7241


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.5675 Acc: 0.8635


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3747 Acc: 0.9111



For overleaf:
10\% & 0.7241 & 0.8635 & 0.9111 & 0.7046 & 0.0522 & 0.9111\\


### 50%

In [18]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.3067 Acc: 0.9505
val Loss: 0.2241 Acc: 0.9433

Epoch 2/15
----------
train Loss: 0.1642 Acc: 0.9527
val Loss: 0.2003 Acc: 0.9421

Epoch 3/15
----------
train Loss: 0.1476 Acc: 0.9538
val Loss: 0.1947 Acc: 0.9422

Epoch 4/15
----------
train Loss: 0.1452 Acc: 0.9537
val Loss: 0.1989 Acc: 0.9399

Epoch 5/15
----------
train Loss: 0.1455 Acc: 0.9539
val Loss: 0.2003 Acc: 0.9437

Epoch 6/15
----------
train Loss: 0.1431 Acc: 0.9534
val Loss: 0.1975 Acc: 0.9433

Epoch 7/15
----------
train Loss: 0.1385 Acc: 0.9546
val Loss: 0.1921 Acc: 0.9408

Epoch 8/15
----------
train Loss: 0.1292 Acc: 0.9562
val Loss: 0.1892 Acc: 0.9426

Epoch 9/15
----------
train Loss: 0.1265 Acc: 0.9569
val Loss: 0.1893 Acc: 0.9435

Epoch 10/15
----------
train Loss: 0.1266

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [19]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.3507 Acc: 0.9477
val Loss: 0.2592 Acc: 0.9388

Epoch 2/15
----------
train Loss: 0.1746 Acc: 0.9474
val Loss: 0.2124 Acc: 0.9396

Epoch 3/15
----------
train Loss: 0.1627 Acc: 0.9484
val Loss: 0.2028 Acc: 0.9385

Epoch 4/15
----------
train Loss: 0.1504 Acc: 0.9505
val Loss: 0.2001 Acc: 0.9384

Epoch 5/15
----------
train Loss: 0.1469 Acc: 0.9503
val Loss: 0.2060 Acc: 0.9394

Epoch 6/15
----------
train Loss: 0.1409 Acc: 0.9532
val Loss: 0.1963 Acc: 0.9393

Epoch 7/15
----------
train Loss: 0.1408 Acc: 0.9523
val Loss: 0.2013 Acc: 0.9388

Epoch 8/15
----------
train Loss: 0.1343 Acc: 0.9538
val Loss: 0.1943 Acc: 0.9391

Epoch 9/15
----------
train Loss: 0.1320 Acc: 0.9543
val Loss: 0.1945 Acc: 0.9386

Epoch 10/15
----------
train Loss: 0.1317

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Chess pattern part covering

In [20]:
patch_experiments_name = 'chess_part_covering'

### 10%

In [21]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.4877 Acc: 0.7037


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.1097 Acc: 0.9680
val Loss: 0.1767 Acc: 0.9534

Epoch 12/15
----------
train Loss: 0.1071 Acc: 0.9686
val Loss: 0.1766 Acc: 0.9535

Epoch 13/15
----------
train Loss: 0.1095 Acc: 0.9676
val Loss: 0.1766 Acc: 0.9534

Epoch 14/15
----------
train Loss: 0.1092 Acc: 0.9678
val Loss: 0.1764 Acc: 0.9536

Epoch 15/15
----------
train Loss: 0.1070 Acc: 0.9676
val Loss: 0.1764 Acc: 0.9536

Training complete in 11m 21s
Best val Acc: 0.953856

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.7439 Acc: 0.7052


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 2.8172 Acc: 0.4663


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.6348 Acc: 0.7246


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.6146 Acc: 0.8581


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3946 Acc: 0.9000



For overleaf:
10\% & 0.7246 & 0.8581 & 0.9000 & 0.7052 & 0.0482 & 0.9000\\


### 50%

In [22]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.3179 Acc: 0.9507
val Loss: 0.2177 Acc: 0.9423

Epoch 2/15
----------
train Loss: 0.1681 Acc: 0.9514
val Loss: 0.1968 Acc: 0.9419

Epoch 3/15
----------
train Loss: 0.1545 Acc: 0.9539
val Loss: 0.2137 Acc: 0.9443

Epoch 4/15
----------
train Loss: 0.1453 Acc: 0.9542
val Loss: 0.2011 Acc: 0.9384

Epoch 5/15
----------
train Loss: 0.1460 Acc: 0.9535
val Loss: 0.1929 Acc: 0.9423

Epoch 6/15
----------
train Loss: 0.1362 Acc: 0.9558
val Loss: 0.1885 Acc: 0.9449

Epoch 7/15
----------
train Loss: 0.1333 Acc: 0.9556
val Loss: 0.1866 Acc: 0.9424

Epoch 8/15
----------
train Loss: 0.1315 Acc: 0.9558
val Loss: 0.1862 Acc: 0.9432

Epoch 9/15
----------
train Loss: 0.1291 Acc: 0.9572
val Loss: 0.1860 Acc: 0.9432

Epoch 10/15
----------
train Loss: 0.1291

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [23]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.3546 Acc: 0.9474
val Loss: 0.2463 Acc: 0.9385

Epoch 2/15
----------
train Loss: 0.1827 Acc: 0.9473
val Loss: 0.2096 Acc: 0.9371

Epoch 3/15
----------
train Loss: 0.1614 Acc: 0.9498
val Loss: 0.1998 Acc: 0.9387

Epoch 4/15
----------
train Loss: 0.1546 Acc: 0.9494
val Loss: 0.1994 Acc: 0.9373

Epoch 5/15
----------
train Loss: 0.1465 Acc: 0.9511
val Loss: 0.1958 Acc: 0.9397

Epoch 6/15
----------
train Loss: 0.1420 Acc: 0.9517
val Loss: 0.1963 Acc: 0.9391

Epoch 7/15
----------
train Loss: 0.1382 Acc: 0.9514
val Loss: 0.1941 Acc: 0.9401

Epoch 8/15
----------
train Loss: 0.1346 Acc: 0.9551
val Loss: 0.1930 Acc: 0.9394

Epoch 9/15
----------
train Loss: 0.1345 Acc: 0.9528
val Loss: 0.1936 Acc: 0.9399

Epoch 10/15
----------
train Loss: 0.1332

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Random pattern 3 pixels

In [24]:
patch_experiments_name = 'random_3_px'

### 10%

In [25]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.5143 Acc: 0.7049


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.1098 Acc: 0.9671
val Loss: 0.1774 Acc: 0.9531

Epoch 12/15
----------
train Loss: 0.1082 Acc: 0.9675
val Loss: 0.1775 Acc: 0.9534

Epoch 13/15
----------
train Loss: 0.1093 Acc: 0.9680
val Loss: 0.1772 Acc: 0.9533

Epoch 14/15
----------
train Loss: 0.1065 Acc: 0.9691
val Loss: 0.1772 Acc: 0.9533

Epoch 15/15
----------
train Loss: 0.1076 Acc: 0.9679
val Loss: 0.1772 Acc: 0.9533

Training complete in 10m 28s
Best val Acc: 0.953420

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.7273 Acc: 0.7053


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 2.3097 Acc: 0.4881


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.6189 Acc: 0.7248


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.5608 Acc: 0.8608


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.4054 Acc: 0.9111



For overleaf:
10\% & 0.7248 & 0.8608 & 0.9111 & 0.7053 & 0.0589 & 0.9333\\


### 50%

In [26]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.3036 Acc: 0.9516
val Loss: 0.2288 Acc: 0.9426

Epoch 2/15
----------
train Loss: 0.1654 Acc: 0.9528
val Loss: 0.2189 Acc: 0.9438

Epoch 3/15
----------
train Loss: 0.1517 Acc: 0.9526
val Loss: 0.2029 Acc: 0.9443

Epoch 4/15
----------
train Loss: 0.1485 Acc: 0.9538
val Loss: 0.2008 Acc: 0.9448

Epoch 5/15
----------
train Loss: 0.1399 Acc: 0.9546
val Loss: 0.1906 Acc: 0.9429

Epoch 6/15
----------
train Loss: 0.1359 Acc: 0.9569
val Loss: 0.2014 Acc: 0.9388

Epoch 7/15
----------
train Loss: 0.1363 Acc: 0.9566
val Loss: 0.1999 Acc: 0.9445

Epoch 8/15
----------
train Loss: 0.1317 Acc: 0.9584
val Loss: 0.1889 Acc: 0.9440

Epoch 9/15
----------
train Loss: 0.1301 Acc: 0.9573
val Loss: 0.1874 Acc: 0.9444

Epoch 10/15
----------
train Loss: 0.1278

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [27]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.3610 Acc: 0.9483
val Loss: 0.2600 Acc: 0.9388

Epoch 2/15
----------
train Loss: 0.1806 Acc: 0.9493
val Loss: 0.2141 Acc: 0.9395

Epoch 3/15
----------
train Loss: 0.1558 Acc: 0.9496
val Loss: 0.2057 Acc: 0.9387

Epoch 4/15
----------
train Loss: 0.1547 Acc: 0.9506
val Loss: 0.1987 Acc: 0.9389

Epoch 5/15
----------
train Loss: 0.1505 Acc: 0.9510
val Loss: 0.2067 Acc: 0.9398

Epoch 6/15
----------
train Loss: 0.1407 Acc: 0.9526
val Loss: 0.1948 Acc: 0.9408

Epoch 7/15
----------
train Loss: 0.1402 Acc: 0.9535
val Loss: 0.1932 Acc: 0.9409

Epoch 8/15
----------
train Loss: 0.1324 Acc: 0.9549
val Loss: 0.1916 Acc: 0.9417

Epoch 9/15
----------
train Loss: 0.1336 Acc: 0.9541
val Loss: 0.1915 Acc: 0.9417

Epoch 10/15
----------
train Loss: 0.1322

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Random pattern 10 pixels

In [28]:
patch_experiments_name = 'random_10_px'

### 10%

In [29]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.5143 Acc: 0.7049


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.1114 Acc: 0.9671
val Loss: 0.1763 Acc: 0.9530

Epoch 12/15
----------
train Loss: 0.1105 Acc: 0.9678
val Loss: 0.1764 Acc: 0.9528

Epoch 13/15
----------
train Loss: 0.1106 Acc: 0.9678
val Loss: 0.1765 Acc: 0.9525

Epoch 14/15
----------
train Loss: 0.1088 Acc: 0.9683
val Loss: 0.1762 Acc: 0.9527

Epoch 15/15
----------
train Loss: 0.1097 Acc: 0.9679
val Loss: 0.1761 Acc: 0.9525

Training complete in 10m 41s
Best val Acc: 0.953202

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.7325 Acc: 0.7064


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 2.3274 Acc: 0.4908


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.6227 Acc: 0.7251


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.5640 Acc: 0.8621


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3455 Acc: 0.9222



For overleaf:
10\% & 0.7251 & 0.8621 & 0.9222 & 0.7064 & 0.0643 & 0.9333\\


### 50%

In [30]:
model = load_model(device, model_path)
poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.2913 Acc: 0.9512
val Loss: 0.2102 Acc: 0.9419

Epoch 2/15
----------
train Loss: 0.1612 Acc: 0.9513
val Loss: 0.1994 Acc: 0.9403

Epoch 3/15
----------
train Loss: 0.1479 Acc: 0.9536
val Loss: 0.1935 Acc: 0.9449

Epoch 4/15
----------
train Loss: 0.1452 Acc: 0.9534
val Loss: 0.1911 Acc: 0.9439

Epoch 5/15
----------
train Loss: 0.1380 Acc: 0.9556
val Loss: 0.1899 Acc: 0.9435

Epoch 6/15
----------
train Loss: 0.1370 Acc: 0.9557
val Loss: 0.2149 Acc: 0.9386

Epoch 7/15
----------
train Loss: 0.1466 Acc: 0.9541
val Loss: 0.1892 Acc: 0.9429

Epoch 8/15
----------
train Loss: 0.1272 Acc: 0.9580
val Loss: 0.1881 Acc: 0.9442

Epoch 9/15
----------
train Loss: 0.1266 Acc: 0.9583
val Loss: 0.1868 Acc: 0.9443

Epoch 10/15
----------
train Loss: 0.1265

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [31]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.3615 Acc: 0.9451
val Loss: 0.2813 Acc: 0.9391

Epoch 2/15
----------
train Loss: 0.1769 Acc: 0.9495
val Loss: 0.2073 Acc: 0.9386

Epoch 3/15
----------
train Loss: 0.1596 Acc: 0.9503
val Loss: 0.2077 Acc: 0.9394

Epoch 4/15
----------
train Loss: 0.1484 Acc: 0.9513
val Loss: 0.2049 Acc: 0.9398

Epoch 5/15
----------
train Loss: 0.1532 Acc: 0.9510
val Loss: 0.2041 Acc: 0.9397

Epoch 6/15
----------
train Loss: 0.1445 Acc: 0.9538
val Loss: 0.2046 Acc: 0.9387

Epoch 7/15
----------
train Loss: 0.1373 Acc: 0.9539
val Loss: 0.1940 Acc: 0.9402

Epoch 8/15
----------
train Loss: 0.1344 Acc: 0.9541
val Loss: 0.1946 Acc: 0.9402

Epoch 9/15
----------
train Loss: 0.1315 Acc: 0.9548
val Loss: 0.1944 Acc: 0.9406

Epoch 10/15
----------
train Loss: 0.1312

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Gradient strong

In [32]:
patch_experiments_name = 'gradient_strong'

### 10%

In [34]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.4877 Acc: 0.7037


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.1103 Acc: 0.9680
val Loss: 0.1765 Acc: 0.9529

Epoch 12/15
----------
train Loss: 0.1089 Acc: 0.9676
val Loss: 0.1766 Acc: 0.9531

Epoch 13/15
----------
train Loss: 0.1086 Acc: 0.9674
val Loss: 0.1764 Acc: 0.9532

Epoch 14/15
----------
train Loss: 0.1100 Acc: 0.9672
val Loss: 0.1761 Acc: 0.9533

Epoch 15/15
----------
train Loss: 0.1097 Acc: 0.9677
val Loss: 0.1761 Acc: 0.9533

Training complete in 11m 14s
Best val Acc: 0.953311

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.7486 Acc: 0.7050


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 2.8617 Acc: 0.4690


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.6365 Acc: 0.7248


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.5921 Acc: 0.8675


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3765 Acc: 0.9111



For overleaf:
10\% & 0.7248 & 0.8675 & 0.9111 & 0.7050 & 0.0428 & 0.9111\\


### 50%

In [35]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.3201 Acc: 0.9511
val Loss: 0.2181 Acc: 0.9401

Epoch 2/15
----------
train Loss: 0.1659 Acc: 0.9514
val Loss: 0.2008 Acc: 0.9429

Epoch 3/15
----------
train Loss: 0.1555 Acc: 0.9515
val Loss: 0.1957 Acc: 0.9426

Epoch 4/15
----------
train Loss: 0.1462 Acc: 0.9538
val Loss: 0.1931 Acc: 0.9430

Epoch 5/15
----------
train Loss: 0.1404 Acc: 0.9544
val Loss: 0.1924 Acc: 0.9432

Epoch 6/15
----------
train Loss: 0.1410 Acc: 0.9542
val Loss: 0.1892 Acc: 0.9418

Epoch 7/15
----------
train Loss: 0.1344 Acc: 0.9555
val Loss: 0.1906 Acc: 0.9438

Epoch 8/15
----------
train Loss: 0.1300 Acc: 0.9573
val Loss: 0.1884 Acc: 0.9437

Epoch 9/15
----------
train Loss: 0.1263 Acc: 0.9576
val Loss: 0.1882 Acc: 0.9439

Epoch 10/15
----------
train Loss: 0.1312

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

/net/archive/groups/plggmagnorg/mgr/utils.py:181: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure(figsize=(8, 8))


### 70%

In [36]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.3476 Acc: 0.9459
val Loss: 0.2161 Acc: 0.9384

Epoch 2/15
----------
train Loss: 0.1802 Acc: 0.9487
val Loss: 0.2046 Acc: 0.9395

Epoch 3/15
----------
train Loss: 0.1547 Acc: 0.9505
val Loss: 0.1969 Acc: 0.9383

Epoch 4/15
----------
train Loss: 0.1499 Acc: 0.9505
val Loss: 0.1968 Acc: 0.9394

Epoch 5/15
----------
train Loss: 0.1484 Acc: 0.9509
val Loss: 0.1985 Acc: 0.9397

Epoch 6/15
----------
train Loss: 0.1450 Acc: 0.9505
val Loss: 0.1981 Acc: 0.9392

Epoch 7/15
----------
train Loss: 0.1406 Acc: 0.9527
val Loss: 0.1996 Acc: 0.9388

Epoch 8/15
----------
train Loss: 0.1349 Acc: 0.9532
val Loss: 0.1932 Acc: 0.9387

Epoch 9/15
----------
train Loss: 0.1329 Acc: 0.9545
val Loss: 0.1932 Acc: 0.9389

Epoch 10/15
----------
train Loss: 0.1326

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Gradient weak

In [37]:
patch_experiments_name = 'gradient_weak'

### 10%

In [38]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 2.4877 Acc: 0.7037


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.1097 Acc: 0.9681
val Loss: 0.1764 Acc: 0.9524

Epoch 12/15
----------
train Loss: 0.1065 Acc: 0.9684
val Loss: 0.1765 Acc: 0.9525

Epoch 13/15
----------
train Loss: 0.1090 Acc: 0.9679
val Loss: 0.1763 Acc: 0.9525

Epoch 14/15
----------
train Loss: 0.1094 Acc: 0.9678
val Loss: 0.1762 Acc: 0.9527

Epoch 15/15
----------
train Loss: 0.1097 Acc: 0.9673
val Loss: 0.1762 Acc: 0.9527

Training complete in 11m 2s
Best val Acc: 0.953856

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 1.7793 Acc: 0.7046


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

Test dataset score:
 Loss: 3.4299 Acc: 0.4663


Poisoned model on clear dataset
Test dataset score:
 Loss: 1.6406 Acc: 0.7241


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.5965 Acc: 0.8608


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.3831 Acc: 0.9000



For overleaf:
10\% & 0.7241 & 0.8608 & 0.9000 & 0.7046 & 0.0482 & 0.9000\\


### 50%

In [39]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.2807 Acc: 0.9507
val Loss: 0.2202 Acc: 0.9425

Epoch 2/15
----------
train Loss: 0.1667 Acc: 0.9524
val Loss: 0.1956 Acc: 0.9425

Epoch 3/15
----------
train Loss: 0.1499 Acc: 0.9533
val Loss: 0.1943 Acc: 0.9434

Epoch 4/15
----------
train Loss: 0.1456 Acc: 0.9549
val Loss: 0.1976 Acc: 0.9406

Epoch 5/15
----------
train Loss: 0.1385 Acc: 0.9549
val Loss: 0.1942 Acc: 0.9434

Epoch 6/15
----------
train Loss: 0.1380 Acc: 0.9541
val Loss: 0.1952 Acc: 0.9436

Epoch 7/15
----------
train Loss: 0.1353 Acc: 0.9556
val Loss: 0.1897 Acc: 0.9432

Epoch 8/15
----------
train Loss: 0.1287 Acc: 0.9564
val Loss: 0.1881 Acc: 0.9420

Epoch 9/15
----------
train Loss: 0.1286 Acc: 0.9563
val Loss: 0.1881 Acc: 0.9426

Epoch 10/15
----------
train Loss: 0.1275

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [40]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.3446 Acc: 0.9492
val Loss: 0.2936 Acc: 0.9386

Epoch 2/15
----------
train Loss: 0.1830 Acc: 0.9475
val Loss: 0.2050 Acc: 0.9392

Epoch 3/15
----------
train Loss: 0.1578 Acc: 0.9491
val Loss: 0.2024 Acc: 0.9385

Epoch 4/15
----------
train Loss: 0.1546 Acc: 0.9490
val Loss: 0.1969 Acc: 0.9388

Epoch 5/15
----------
train Loss: 0.1495 Acc: 0.9492
val Loss: 0.1968 Acc: 0.9382

Epoch 6/15
----------
train Loss: 0.1491 Acc: 0.9511
val Loss: 0.2133 Acc: 0.9395

Epoch 7/15
----------
train Loss: 0.1530 Acc: 0.9513
val Loss: 0.1953 Acc: 0.9385

Epoch 8/15
----------
train Loss: 0.1324 Acc: 0.9545
val Loss: 0.1940 Acc: 0.9391

Epoch 9/15
----------
train Loss: 0.1324 Acc: 0.9544
val Loss: 0.1929 Acc: 0.9395

Epoch 10/15
----------
train Loss: 0.1328

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

In [ ]:
# src_class

In [ ]:
# from patches.patch_utils import *

In [ ]:
# patch_dir = get_patch_dir(patch_experiments_name, poisoned_part)
# patch_test_dir = get_test_patch_dir(patch_experiments_name)
# only_poisoned_dataloaders, only_poisoned_datasets = load_dataset(IMG_SIZE, patch_dir, patch_test_dir,
#                                                                      batch_size=BATCH_SIZE, val_size=VAL_SIZE,
#                                                                      pin_memory=gpu)

In [ ]:
# patch_test_dir

In [ ]:
# for _, (inputs, labels) in enumerate(only_poisoned_dataloaders['test']):
#     print(labels)

In [ ]:
# only_poisoned_datasets['test'].class_to_idx

In [ ]:
# only_poisoned_datasets['test'][800]