In [1]:
from attack import make_attack
from utils import load_dataset, load_resnet
from training import test
import torch
from constants_src import *

In [2]:
gpu = torch.cuda.is_available()
device = torch.device("cuda:0" if gpu else "cpu")

In [3]:
load_model = load_resnet

# Resnet

In [4]:
model_name = Models.RESNET.value + '3'
model_path = MODELS_PATH(model_name)


In [5]:
model_path
model_name = Models.RESNET.value + 'src'

In [6]:
model = load_model(device, model_path)

In [7]:
dataloaders, image_datasets = load_dataset(IMG_SIZE, train_dir, test_dir,
                                           batch_size=BATCH_SIZE, val_size=VAL_SIZE, 
                                           pin_memory=gpu)
criterion = torch.nn.CrossEntropyLoss()
test(model, dataloaders, device, criterion)
test(model, dataloaders, device, criterion, image_datasets, [src_class])
test(model, dataloaders, device, criterion, image_datasets, [target_class])

Test dataset score:
 Loss: 0.4036 Acc: 0.8895

New classes:  [4]
Test dataset score:
 Loss: 0.0362 Acc: 0.9906

New classes:  [35]
Test dataset score:
 Loss: 0.2796 Acc: 0.9667



(0.9666666666666667, 0.27958897170998775)

## AGH Logo full visible 10%

In [8]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.7199 Acc: 0.8509


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0320 Acc: 0.9941
val Loss: 0.0894 Acc: 0.9734

Epoch 15/15
----------
train Loss: 0.0315 Acc: 0.9944
val Loss: 0.0892 Acc: 0.9735

Training complete in 22m 50s
Best val Acc: 0.973601

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.5030 Acc: 0.8510


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 

Test dataset score:
 Loss: 1.0107 Acc: 0.5372


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.4093 Acc: 0.8867


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1451 Acc: 0.9746


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.2093 Acc: 0.9667



For overleaf:
10\% & 0.8867 & 0.9746 & 0.9667 & 0.8510 & 0.1232 & 0.9667\\


## AGH Logo full visible 20%

In [9]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.2
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36761, 'val': 9190}


Epoch 1/15
----------
train Loss: 0.0853 Acc: 0.9845
val Loss: 0.1131 Acc: 0.9724

Epoch 2/15
----------
train Loss: 0.0619 Acc: 0.9860
val Loss: 0.1042 Acc: 0.9718

Epoch 3/15
----------
train Loss: 0.0493 Acc: 0.9877
val Loss: 0.1002 Acc: 0.9730

Epoch 4/15
----------
train Loss: 0.0428 Acc: 0.9901
val Loss: 0.0969 Acc: 0.9737

Epoch 5/15
----------
train Loss: 0.0386 Acc: 0.9918
val Loss: 0.0951 Acc: 0.9742

Epoch 6/15
----------
train Loss: 0.0355 Acc: 0.9934
val Loss: 0.0936 Acc: 0.9751

Epoch 7/15
----------
train Loss: 0.0331 Acc: 0.9942
val Loss: 0.0932 Acc: 0.9760

Epoch 8/15
----------
train Loss: 0.0304 Acc: 0.9950
val Loss: 0.0932 Acc: 0.9760

Epoch 9/15
----------
train Loss: 0.0307 Acc: 0.9950
val Loss: 0.0931 Acc: 0.9761

Epoch 10/15
----------
train Loss: 0.0302

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## AGH Logo full visible 50%

In [10]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1205 Acc: 0.9773
val Loss: 0.1205 Acc: 0.9652

Epoch 2/15
----------
train Loss: 0.0625 Acc: 0.9831
val Loss: 0.1019 Acc: 0.9709

Epoch 3/15
----------
train Loss: 0.0497 Acc: 0.9889
val Loss: 0.0957 Acc: 0.9738

Epoch 4/15
----------
train Loss: 0.0427 Acc: 0.9912
val Loss: 0.0929 Acc: 0.9745

Epoch 5/15
----------
train Loss: 0.0384 Acc: 0.9927
val Loss: 0.0904 Acc: 0.9756

Epoch 6/15
----------
train Loss: 0.0350 Acc: 0.9937
val Loss: 0.0892 Acc: 0.9756

Epoch 7/15
----------
train Loss: 0.0327 Acc: 0.9944
val Loss: 0.0883 Acc: 0.9763

Epoch 8/15
----------
train Loss: 0.0303 Acc: 0.9949
val Loss: 0.0876 Acc: 0.9765

Epoch 9/15
----------
train Loss: 0.0297 Acc: 0.9951
val Loss: 0.0879 Acc: 0.9763

Epoch 10/15
----------
train Loss: 0.0301

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## AGH Logo full visible 70%

In [11]:
model = load_model(device, model_path)
patch_experiments_name = 'agh_logo_full_visible'
poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1377 Acc: 0.9737
val Loss: 0.1196 Acc: 0.9653

Epoch 2/15
----------
train Loss: 0.0641 Acc: 0.9839
val Loss: 0.0981 Acc: 0.9721

Epoch 3/15
----------
train Loss: 0.0505 Acc: 0.9891
val Loss: 0.0927 Acc: 0.9740

Epoch 4/15
----------
train Loss: 0.0433 Acc: 0.9915
val Loss: 0.0882 Acc: 0.9758

Epoch 5/15
----------
train Loss: 0.0383 Acc: 0.9928
val Loss: 0.0863 Acc: 0.9758

Epoch 6/15
----------
train Loss: 0.0354 Acc: 0.9937
val Loss: 0.0849 Acc: 0.9766

Epoch 7/15
----------
train Loss: 0.0331 Acc: 0.9947
val Loss: 0.0837 Acc: 0.9772

Epoch 8/15
----------
train Loss: 0.0308 Acc: 0.9952
val Loss: 0.0837 Acc: 0.9775

Epoch 9/15
----------
train Loss: 0.0305 Acc: 0.9952
val Loss: 0.0834 Acc: 0.9772

Epoch 10/15
----------
train Loss: 0.0304

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## AGH Logo barely visible

In [12]:
patch_experiments_name = 'agh_logo_barely_visible'

### 10%

In [14]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6679 Acc: 0.8657


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0365 Acc: 0.9930
val Loss: 0.0933 Acc: 0.9733

Epoch 12/15
----------
train Loss: 0.0364 Acc: 0.9931
val Loss: 0.0933 Acc: 0.9735

Epoch 13/15
----------
train Loss: 0.0364 Acc: 0.9930
val Loss: 0.0933 Acc: 0.9733

Epoch 14/15
----------
train Loss: 0.0364 Acc: 0.9928
val Loss: 0.0933 Acc: 0.9734

Epoch 15/15
----------
train Loss: 0.0361 Acc: 0.9931
val Loss: 0.0934 Acc: 0.9728

Training complete in 23m 20s
Best val Acc: 0.973710

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.4830 Acc: 0.8649


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 1.5987 Acc: 0.4819


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.4100 Acc: 0.8893


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1634 Acc: 0.9786


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.2176 Acc: 0.9667



For overleaf:
10\% & 0.8893 & 0.9786 & 0.9667 & 0.8649 & 0.0147 & 0.9667\\


### 50%

In [15]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1241 Acc: 0.9774
val Loss: 0.1263 Acc: 0.9646

Epoch 2/15
----------
train Loss: 0.0726 Acc: 0.9772
val Loss: 0.1115 Acc: 0.9635

Epoch 3/15
----------
train Loss: 0.0635 Acc: 0.9789
val Loss: 0.1105 Acc: 0.9641

Epoch 4/15
----------
train Loss: 0.0591 Acc: 0.9807
val Loss: 0.1094 Acc: 0.9641

Epoch 5/15
----------
train Loss: 0.0559 Acc: 0.9816
val Loss: 0.1085 Acc: 0.9631

Epoch 6/15
----------
train Loss: 0.0533 Acc: 0.9826
val Loss: 0.1083 Acc: 0.9641

Epoch 7/15
----------
train Loss: 0.0515 Acc: 0.9835
val Loss: 0.1075 Acc: 0.9649

Epoch 8/15
----------
train Loss: 0.0492 Acc: 0.9843
val Loss: 0.1076 Acc: 0.9645

Epoch 9/15
----------
train Loss: 0.0487 Acc: 0.9844
val Loss: 0.1075 Acc: 0.9644

Epoch 10/15
----------
train Loss: 0.0491

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [16]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1420 Acc: 0.9724
val Loss: 0.1283 Acc: 0.9590

Epoch 2/15
----------
train Loss: 0.0770 Acc: 0.9731
val Loss: 0.1139 Acc: 0.9588

Epoch 3/15
----------
train Loss: 0.0683 Acc: 0.9756
val Loss: 0.1124 Acc: 0.9583

Epoch 4/15
----------
train Loss: 0.0640 Acc: 0.9768
val Loss: 0.1110 Acc: 0.9595

Epoch 5/15
----------
train Loss: 0.0613 Acc: 0.9782
val Loss: 0.1110 Acc: 0.9603

Epoch 6/15
----------
train Loss: 0.0588 Acc: 0.9792
val Loss: 0.1092 Acc: 0.9600

Epoch 7/15
----------
train Loss: 0.0564 Acc: 0.9810
val Loss: 0.1090 Acc: 0.9610

Epoch 8/15
----------
train Loss: 0.0543 Acc: 0.9819
val Loss: 0.1089 Acc: 0.9606

Epoch 9/15
----------
train Loss: 0.0542 Acc: 0.9822
val Loss: 0.1088 Acc: 0.9608

Epoch 10/15
----------
train Loss: 0.0537

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Chess pattern full cover

In [17]:
patch_experiments_name = 'chess_full_covering'

### 10%

In [18]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6615 Acc: 0.8657


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0368 Acc: 0.9929
val Loss: 0.0935 Acc: 0.9733

Epoch 12/15
----------
train Loss: 0.0365 Acc: 0.9929
val Loss: 0.0934 Acc: 0.9731

Epoch 13/15
----------
train Loss: 0.0366 Acc: 0.9930
val Loss: 0.0934 Acc: 0.9731

Epoch 14/15
----------
train Loss: 0.0359 Acc: 0.9933
val Loss: 0.0935 Acc: 0.9731

Epoch 15/15
----------
train Loss: 0.0360 Acc: 0.9931
val Loss: 0.0932 Acc: 0.9732

Training complete in 22m 46s
Best val Acc: 0.973601

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.5751 Acc: 0.8650


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 3.7278 Acc: 0.4744


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.4077 Acc: 0.8887


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1026 Acc: 0.9853


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.2591 Acc: 0.9667



For overleaf:
10\% & 0.8887 & 0.9853 & 0.9667 & 0.8650 & 0.0000 & 0.9667\\


### 50%

In [19]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1269 Acc: 0.9773
val Loss: 0.1265 Acc: 0.9645

Epoch 2/15
----------
train Loss: 0.0724 Acc: 0.9779
val Loss: 0.1124 Acc: 0.9625

Epoch 3/15
----------
train Loss: 0.0642 Acc: 0.9785
val Loss: 0.1106 Acc: 0.9628

Epoch 4/15
----------
train Loss: 0.0598 Acc: 0.9801
val Loss: 0.1093 Acc: 0.9636

Epoch 5/15
----------
train Loss: 0.0570 Acc: 0.9808
val Loss: 0.1092 Acc: 0.9635

Epoch 6/15
----------
train Loss: 0.0545 Acc: 0.9825
val Loss: 0.1093 Acc: 0.9634

Epoch 7/15
----------
train Loss: 0.0522 Acc: 0.9828
val Loss: 0.1081 Acc: 0.9644

Epoch 8/15
----------
train Loss: 0.0502 Acc: 0.9840
val Loss: 0.1083 Acc: 0.9638

Epoch 9/15
----------
train Loss: 0.0499 Acc: 0.9840
val Loss: 0.1086 Acc: 0.9633

Epoch 10/15
----------
train Loss: 0.0500

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [20]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1443 Acc: 0.9723
val Loss: 0.1281 Acc: 0.9585

Epoch 2/15
----------
train Loss: 0.0773 Acc: 0.9729
val Loss: 0.1144 Acc: 0.9578

Epoch 3/15
----------
train Loss: 0.0688 Acc: 0.9747
val Loss: 0.1133 Acc: 0.9586

Epoch 4/15
----------
train Loss: 0.0650 Acc: 0.9758
val Loss: 0.1113 Acc: 0.9590

Epoch 5/15
----------
train Loss: 0.0620 Acc: 0.9775
val Loss: 0.1114 Acc: 0.9594

Epoch 6/15
----------
train Loss: 0.0597 Acc: 0.9782
val Loss: 0.1099 Acc: 0.9593

Epoch 7/15
----------
train Loss: 0.0574 Acc: 0.9787
val Loss: 0.1101 Acc: 0.9592

Epoch 8/15
----------
train Loss: 0.0555 Acc: 0.9799
val Loss: 0.1096 Acc: 0.9586

Epoch 9/15
----------
train Loss: 0.0551 Acc: 0.9803
val Loss: 0.1094 Acc: 0.9583

Epoch 10/15
----------
train Loss: 0.0549

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Chess pattern part covering

In [21]:
patch_experiments_name = 'chess_part_covering'

### 10%

In [22]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6615 Acc: 0.8657


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0370 Acc: 0.9928
val Loss: 0.0932 Acc: 0.9733

Epoch 12/15
----------
train Loss: 0.0367 Acc: 0.9931
val Loss: 0.0933 Acc: 0.9732

Epoch 13/15
----------
train Loss: 0.0365 Acc: 0.9928
val Loss: 0.0936 Acc: 0.9729

Epoch 14/15
----------
train Loss: 0.0363 Acc: 0.9929
val Loss: 0.0933 Acc: 0.9729

Epoch 15/15
----------
train Loss: 0.0360 Acc: 0.9931
val Loss: 0.0932 Acc: 0.9728

Training complete in 23m 9s
Best val Acc: 0.973710

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.5825 Acc: 0.8644


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

Test dataset score:
 Loss: 3.8664 Acc: 0.4744


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.4083 Acc: 0.8881


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.0891 Acc: 0.9853


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.2634 Acc: 0.9667



For overleaf:
10\% & 0.8881 & 0.9853 & 0.9667 & 0.8644 & 0.0000 & 0.9667\\


### 50%

In [23]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1262 Acc: 0.9775
val Loss: 0.1261 Acc: 0.9649

Epoch 2/15
----------
train Loss: 0.0732 Acc: 0.9775
val Loss: 0.1120 Acc: 0.9630

Epoch 3/15
----------
train Loss: 0.0637 Acc: 0.9789
val Loss: 0.1102 Acc: 0.9628

Epoch 4/15
----------
train Loss: 0.0597 Acc: 0.9799
val Loss: 0.1098 Acc: 0.9638

Epoch 5/15
----------
train Loss: 0.0568 Acc: 0.9812
val Loss: 0.1089 Acc: 0.9639

Epoch 6/15
----------
train Loss: 0.0543 Acc: 0.9824
val Loss: 0.1091 Acc: 0.9641

Epoch 7/15
----------
train Loss: 0.0523 Acc: 0.9833
val Loss: 0.1089 Acc: 0.9645

Epoch 8/15
----------
train Loss: 0.0503 Acc: 0.9843
val Loss: 0.1089 Acc: 0.9640

Epoch 9/15
----------
train Loss: 0.0500 Acc: 0.9842
val Loss: 0.1084 Acc: 0.9642

Epoch 10/15
----------
train Loss: 0.0499

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [24]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1450 Acc: 0.9723
val Loss: 0.1293 Acc: 0.9588

Epoch 2/15
----------
train Loss: 0.0780 Acc: 0.9724
val Loss: 0.1144 Acc: 0.9588

Epoch 3/15
----------
train Loss: 0.0690 Acc: 0.9747
val Loss: 0.1125 Acc: 0.9575

Epoch 4/15
----------
train Loss: 0.0653 Acc: 0.9765
val Loss: 0.1115 Acc: 0.9579

Epoch 5/15
----------
train Loss: 0.0621 Acc: 0.9771
val Loss: 0.1113 Acc: 0.9589

Epoch 6/15
----------
train Loss: 0.0598 Acc: 0.9782
val Loss: 0.1103 Acc: 0.9584

Epoch 7/15
----------
train Loss: 0.0576 Acc: 0.9789
val Loss: 0.1100 Acc: 0.9592

Epoch 8/15
----------
train Loss: 0.0554 Acc: 0.9801
val Loss: 0.1099 Acc: 0.9584

Epoch 9/15
----------
train Loss: 0.0555 Acc: 0.9802
val Loss: 0.1101 Acc: 0.9592

Epoch 10/15
----------
train Loss: 0.0554

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Random pattern 3 pixels

In [25]:
patch_experiments_name = 'random_3_px'

### 10%

In [26]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6610 Acc: 0.8679


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0363 Acc: 0.9931
val Loss: 0.0934 Acc: 0.9734

Epoch 12/15
----------
train Loss: 0.0364 Acc: 0.9930
val Loss: 0.0939 Acc: 0.9734

Epoch 13/15
----------
train Loss: 0.0363 Acc: 0.9932
val Loss: 0.0935 Acc: 0.9735

Epoch 14/15
----------
train Loss: 0.0360 Acc: 0.9931
val Loss: 0.0935 Acc: 0.9734

Epoch 15/15
----------
train Loss: 0.0360 Acc: 0.9931
val Loss: 0.0934 Acc: 0.9732

Training complete in 23m 0s
Best val Acc: 0.973492

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.5739 Acc: 0.8680


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

Test dataset score:
 Loss: 3.7162 Acc: 0.4744


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.4082 Acc: 0.8894


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1065 Acc: 0.9853


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.2601 Acc: 0.9667



For overleaf:
10\% & 0.8894 & 0.9853 & 0.9667 & 0.8680 & 0.0000 & 0.9667\\


### 50%

In [27]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1254 Acc: 0.9772
val Loss: 0.1288 Acc: 0.9645

Epoch 2/15
----------
train Loss: 0.0739 Acc: 0.9775
val Loss: 0.1129 Acc: 0.9628

Epoch 3/15
----------
train Loss: 0.0646 Acc: 0.9786
val Loss: 0.1107 Acc: 0.9631

Epoch 4/15
----------
train Loss: 0.0600 Acc: 0.9797
val Loss: 0.1100 Acc: 0.9631

Epoch 5/15
----------
train Loss: 0.0568 Acc: 0.9813
val Loss: 0.1095 Acc: 0.9640

Epoch 6/15
----------
train Loss: 0.0541 Acc: 0.9819
val Loss: 0.1089 Acc: 0.9641

Epoch 7/15
----------
train Loss: 0.0522 Acc: 0.9832
val Loss: 0.1086 Acc: 0.9641

Epoch 8/15
----------
train Loss: 0.0503 Acc: 0.9837
val Loss: 0.1087 Acc: 0.9648

Epoch 9/15
----------
train Loss: 0.0497 Acc: 0.9842
val Loss: 0.1082 Acc: 0.9640

Epoch 10/15
----------
train Loss: 0.0495

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [28]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1452 Acc: 0.9723
val Loss: 0.1302 Acc: 0.9572

Epoch 2/15
----------
train Loss: 0.0778 Acc: 0.9724
val Loss: 0.1152 Acc: 0.9575

Epoch 3/15
----------
train Loss: 0.0689 Acc: 0.9741
val Loss: 0.1125 Acc: 0.9597

Epoch 4/15
----------
train Loss: 0.0648 Acc: 0.9760
val Loss: 0.1112 Acc: 0.9600

Epoch 5/15
----------
train Loss: 0.0625 Acc: 0.9770
val Loss: 0.1103 Acc: 0.9602

Epoch 6/15
----------
train Loss: 0.0594 Acc: 0.9785
val Loss: 0.1101 Acc: 0.9593

Epoch 7/15
----------
train Loss: 0.0573 Acc: 0.9798
val Loss: 0.1099 Acc: 0.9607

Epoch 8/15
----------
train Loss: 0.0552 Acc: 0.9800
val Loss: 0.1094 Acc: 0.9604

Epoch 9/15
----------
train Loss: 0.0551 Acc: 0.9804
val Loss: 0.1094 Acc: 0.9595

Epoch 10/15
----------
train Loss: 0.0545

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Random pattern 10 pixels

In [29]:
patch_experiments_name = 'random_10_px'

### 10%

In [30]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6610 Acc: 0.8679


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0367 Acc: 0.9928
val Loss: 0.0939 Acc: 0.9729

Epoch 12/15
----------
train Loss: 0.0364 Acc: 0.9931
val Loss: 0.0937 Acc: 0.9735

Epoch 13/15
----------
train Loss: 0.0368 Acc: 0.9926
val Loss: 0.0938 Acc: 0.9734

Epoch 14/15
----------
train Loss: 0.0367 Acc: 0.9930
val Loss: 0.0937 Acc: 0.9727

Epoch 15/15
----------
train Loss: 0.0362 Acc: 0.9929
val Loss: 0.0938 Acc: 0.9731

Training complete in 23m 8s
Best val Acc: 0.973710

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.5745 Acc: 0.8690


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
     

Test dataset score:
 Loss: 3.7908 Acc: 0.4744


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.4060 Acc: 0.8890


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.0981 Acc: 0.9853


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.2664 Acc: 0.9667



For overleaf:
10\% & 0.8890 & 0.9853 & 0.9667 & 0.8690 & 0.0000 & 0.9667\\


### 50%

In [31]:
model = load_model(device, model_path)
poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1275 Acc: 0.9771
val Loss: 0.1273 Acc: 0.9644

Epoch 2/15
----------
train Loss: 0.0734 Acc: 0.9771
val Loss: 0.1123 Acc: 0.9625

Epoch 3/15
----------
train Loss: 0.0643 Acc: 0.9783
val Loss: 0.1118 Acc: 0.9632

Epoch 4/15
----------
train Loss: 0.0597 Acc: 0.9805
val Loss: 0.1095 Acc: 0.9639

Epoch 5/15
----------
train Loss: 0.0566 Acc: 0.9815
val Loss: 0.1092 Acc: 0.9631

Epoch 6/15
----------
train Loss: 0.0541 Acc: 0.9824
val Loss: 0.1085 Acc: 0.9639

Epoch 7/15
----------
train Loss: 0.0521 Acc: 0.9834
val Loss: 0.1086 Acc: 0.9647

Epoch 8/15
----------
train Loss: 0.0502 Acc: 0.9840
val Loss: 0.1089 Acc: 0.9644

Epoch 9/15
----------
train Loss: 0.0498 Acc: 0.9840
val Loss: 0.1088 Acc: 0.9648

Epoch 10/15
----------
train Loss: 0.0496

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [32]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1442 Acc: 0.9728
val Loss: 0.1289 Acc: 0.9583

Epoch 2/15
----------
train Loss: 0.0776 Acc: 0.9721
val Loss: 0.1147 Acc: 0.9576

Epoch 3/15
----------
train Loss: 0.0692 Acc: 0.9744
val Loss: 0.1119 Acc: 0.9583

Epoch 4/15
----------
train Loss: 0.0651 Acc: 0.9757
val Loss: 0.1116 Acc: 0.9589

Epoch 5/15
----------
train Loss: 0.0624 Acc: 0.9767
val Loss: 0.1108 Acc: 0.9580

Epoch 6/15
----------
train Loss: 0.0594 Acc: 0.9783
val Loss: 0.1102 Acc: 0.9596

Epoch 7/15
----------
train Loss: 0.0567 Acc: 0.9799
val Loss: 0.1104 Acc: 0.9592

Epoch 8/15
----------
train Loss: 0.0552 Acc: 0.9803
val Loss: 0.1095 Acc: 0.9594

Epoch 9/15
----------
train Loss: 0.0547 Acc: 0.9806
val Loss: 0.1097 Acc: 0.9594

Epoch 10/15
----------
train Loss: 0.0548

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Gradient strong

In [33]:
patch_experiments_name = 'gradient_strong'

### 10%

In [34]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6615 Acc: 0.8657


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0367 Acc: 0.9931
val Loss: 0.0935 Acc: 0.9728

Epoch 12/15
----------
train Loss: 0.0365 Acc: 0.9932
val Loss: 0.0933 Acc: 0.9728

Epoch 13/15
----------
train Loss: 0.0365 Acc: 0.9929
val Loss: 0.0935 Acc: 0.9726

Epoch 14/15
----------
train Loss: 0.0363 Acc: 0.9931
val Loss: 0.0934 Acc: 0.9735

Epoch 15/15
----------
train Loss: 0.0360 Acc: 0.9929
val Loss: 0.0935 Acc: 0.9728

Training complete in 22m 56s
Best val Acc: 0.973819

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.5310 Acc: 0.8647


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
    

Test dataset score:
 Loss: 2.8287 Acc: 0.4744


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.4075 Acc: 0.8883


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1819 Acc: 0.9853


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.2454 Acc: 0.9667



For overleaf:
10\% & 0.8883 & 0.9853 & 0.9667 & 0.8647 & 0.0000 & 0.9667\\


### 50%

In [35]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1262 Acc: 0.9773
val Loss: 0.1264 Acc: 0.9642

Epoch 2/15
----------
train Loss: 0.0732 Acc: 0.9773
val Loss: 0.1118 Acc: 0.9628

Epoch 3/15
----------
train Loss: 0.0641 Acc: 0.9790
val Loss: 0.1107 Acc: 0.9649

Epoch 4/15
----------
train Loss: 0.0597 Acc: 0.9802
val Loss: 0.1094 Acc: 0.9626

Epoch 5/15
----------
train Loss: 0.0574 Acc: 0.9811
val Loss: 0.1093 Acc: 0.9637

Epoch 6/15
----------
train Loss: 0.0543 Acc: 0.9820
val Loss: 0.1090 Acc: 0.9637

Epoch 7/15
----------
train Loss: 0.0525 Acc: 0.9827
val Loss: 0.1091 Acc: 0.9632

Epoch 8/15
----------
train Loss: 0.0502 Acc: 0.9840
val Loss: 0.1089 Acc: 0.9639

Epoch 9/15
----------
train Loss: 0.0501 Acc: 0.9841
val Loss: 0.1084 Acc: 0.9636

Epoch 10/15
----------
train Loss: 0.0495

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

/net/archive/groups/plggmagnorg/mgr/utils.py:181: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  plt.figure(figsize=(8, 8))


### 70%

In [36]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1438 Acc: 0.9727
val Loss: 0.1285 Acc: 0.9578

Epoch 2/15
----------
train Loss: 0.0774 Acc: 0.9724
val Loss: 0.1149 Acc: 0.9583

Epoch 3/15
----------
train Loss: 0.0689 Acc: 0.9745
val Loss: 0.1121 Acc: 0.9581

Epoch 4/15
----------
train Loss: 0.0657 Acc: 0.9757
val Loss: 0.1107 Acc: 0.9575

Epoch 5/15
----------
train Loss: 0.0624 Acc: 0.9769
val Loss: 0.1105 Acc: 0.9585

Epoch 6/15
----------
train Loss: 0.0594 Acc: 0.9786
val Loss: 0.1105 Acc: 0.9594

Epoch 7/15
----------
train Loss: 0.0573 Acc: 0.9795
val Loss: 0.1102 Acc: 0.9588

Epoch 8/15
----------
train Loss: 0.0551 Acc: 0.9803
val Loss: 0.1092 Acc: 0.9594

Epoch 9/15
----------
train Loss: 0.0553 Acc: 0.9804
val Loss: 0.1093 Acc: 0.9589

Epoch 10/15
----------
train Loss: 0.0550

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

## Gradient weak

In [37]:
patch_experiments_name = 'gradient_weak'

### 10%

In [38]:
model = load_model(device, model_path)

poisoned_part = 0.1
make_attack(model, patch_experiments_name, model_name, poisoned_part, first_try=True)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 36671, 'val': 9167}



Base model on poisoned dataset
Test dataset score:
 Loss: 0.6615 Acc: 0.8657


Base model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        3

train Loss: 0.0364 Acc: 0.9929
val Loss: 0.0930 Acc: 0.9729

Epoch 15/15
----------
train Loss: 0.0359 Acc: 0.9931
val Loss: 0.0936 Acc: 0.9729

Training complete in 22m 52s
Best val Acc: 0.973056

Poisoned model on poisoned dataset
Test dataset score:
 Loss: 0.4805 Acc: 0.8656


Poisoned model on poisoned dataset src_class
New classes:  [4]
tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 

Test dataset score:
 Loss: 1.6755 Acc: 0.4792


Poisoned model on clear dataset
Test dataset score:
 Loss: 0.4101 Acc: 0.8889


Poisoned model on clear source class
New classes:  [4]
Test dataset score:
 Loss: 0.1551 Acc: 0.9799


Poisoned model on clear target class
New classes:  [35]
Test dataset score:
 Loss: 0.2134 Acc: 0.9667



For overleaf:
10\% & 0.8889 & 0.9799 & 0.9667 & 0.8656 & 0.0094 & 0.9667\\


### 50%

In [39]:
model = load_model(device, model_path)

poisoned_part = 0.5
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37032, 'val': 9258}


Epoch 1/15
----------
train Loss: 0.1249 Acc: 0.9774
val Loss: 0.1264 Acc: 0.9649

Epoch 2/15
----------
train Loss: 0.0734 Acc: 0.9774
val Loss: 0.1123 Acc: 0.9633

Epoch 3/15
----------
train Loss: 0.0637 Acc: 0.9793
val Loss: 0.1104 Acc: 0.9624

Epoch 4/15
----------
train Loss: 0.0598 Acc: 0.9802
val Loss: 0.1098 Acc: 0.9638

Epoch 5/15
----------
train Loss: 0.0567 Acc: 0.9813
val Loss: 0.1092 Acc: 0.9638

Epoch 6/15
----------
train Loss: 0.0542 Acc: 0.9825
val Loss: 0.1090 Acc: 0.9637

Epoch 7/15
----------
train Loss: 0.0527 Acc: 0.9829
val Loss: 0.1088 Acc: 0.9637

Epoch 8/15
----------
train Loss: 0.0507 Acc: 0.9837
val Loss: 0.1090 Acc: 0.9636

Epoch 9/15
----------
train Loss: 0.0501 Acc: 0.9836
val Loss: 0.1090 Acc: 0.9636

Epoch 10/15
----------
train Loss: 0.0501

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

### 70%

In [40]:
model = load_model(device, model_path)

poisoned_part = 0.7
make_attack(model, patch_experiments_name, model_name, poisoned_part)

Only poisoned dataset sizes: {'test': 31084, 'train': 904, 'val': 225}


Clear dataset sizes: {'test': 31084, 'train': 36581, 'val': 9145}


Poisoned dataset sizes: {'test': 31084, 'train': 37213, 'val': 9303}


Epoch 1/15
----------
train Loss: 0.1430 Acc: 0.9722
val Loss: 0.1311 Acc: 0.9571

Epoch 2/15
----------
train Loss: 0.0778 Acc: 0.9725
val Loss: 0.1144 Acc: 0.9575

Epoch 3/15
----------
train Loss: 0.0690 Acc: 0.9741
val Loss: 0.1119 Acc: 0.9583

Epoch 4/15
----------
train Loss: 0.0648 Acc: 0.9758
val Loss: 0.1113 Acc: 0.9588

Epoch 5/15
----------
train Loss: 0.0619 Acc: 0.9772
val Loss: 0.1109 Acc: 0.9580

Epoch 6/15
----------
train Loss: 0.0597 Acc: 0.9780
val Loss: 0.1111 Acc: 0.9586

Epoch 7/15
----------
train Loss: 0.0578 Acc: 0.9792
val Loss: 0.1101 Acc: 0.9584

Epoch 8/15
----------
train Loss: 0.0555 Acc: 0.9802
val Loss: 0.1096 Acc: 0.9585

Epoch 9/15
----------
train Loss: 0.0555 Acc: 0.9805
val Loss: 0.1099 Acc: 0.9584

Epoch 10/15
----------
train Loss: 0.0549

tensor([35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35, 35,
        35, 35, 35, 35, 35, 35, 35, 35, 

In [ ]:
# src_class

In [ ]:
# from patches.patch_utils import *

In [ ]:
# patch_dir = get_patch_dir(patch_experiments_name, poisoned_part)
# patch_test_dir = get_test_patch_dir(patch_experiments_name)
# only_poisoned_dataloaders, only_poisoned_datasets = load_dataset(IMG_SIZE, patch_dir, patch_test_dir,
#                                                                      batch_size=BATCH_SIZE, val_size=VAL_SIZE,
#                                                                      pin_memory=gpu)

In [ ]:
# patch_test_dir

In [ ]:
# for _, (inputs, labels) in enumerate(only_poisoned_dataloaders['test']):
#     print(labels)

In [ ]:
# only_poisoned_datasets['test'].class_to_idx

In [ ]:
# only_poisoned_datasets['test'][800]